/** Structural guards for the S3-01b thin-client boundary. */
import { readFileSync, readdirSync, statSync } from "fs";
import { join, relative } from "path";

const WEB_ROOT = join(__dirname, "..");
const APP_ROOT = join(WEB_ROOT, "app");
const CLIENT_FILE = "app/api/decision-service.ts";
const GENERATED_FILE = "app/api/generated.ts";

function sourceFiles(directory: string): string[] {
  return readdirSync(directory).flatMap((entry) => {
    const absolute = join(directory, entry);
    if (statSync(absolute).isDirectory()) return sourceFiles(absolute);
    if (!/\.tsx?$/.test(entry) || /\.test\.tsx?$/.test(entry)) return [];
    return [relative(WEB_ROOT, absolute)];
  });
}

function read(relativePath: string): string {
  return readFileSync(join(WEB_ROOT, relativePath), "utf8");
}

const HAND_WRITTEN_SOURCES = sourceFiles(APP_ROOT).filter(
  (file) => file !== GENERATED_FILE,
);

describe("S3-01b frontend architecture", () => {
  it("uses one shared integration module for all direct HTTP access", () => {
    const directHttpSources = HAND_WRITTEN_SOURCES.filter((file) => {
      const code = read(file);
      return /from\s+["']openapi-fetch["']|\bfetch\s*\(|\baxios\b/.test(code);
    });
    expect(directHttpSources).toEqual([CLIENT_FILE]);
  });

  it("reads the configurable API base URL only inside the shared client", () => {
    const envReaders = HAND_WRITTEN_SOURCES.filter((file) =>
      /process\.env\.NEXT_PUBLIC_API_BASE_URL/.test(read(file)),
    );
    expect(envReaders).toEqual([CLIENT_FILE]);
  });

  it.each(HAND_WRITTEN_SOURCES)(
    "%s contains no hard-coded HTTP host",
    (file) => {
      expect(read(file)).not.toMatch(/["'`]https?:\/\//);
    },
  );

  it.each(HAND_WRITTEN_SOURCES)(
    "%s contains no scoring, normalisation, ranking or exclusion computation",
    (file) => {
      const code = read(file);
      expect(code).not.toMatch(
        /\b(computeScore|computeRank|rankCells|weightedSum|applyWeights|normalise|normalize|exclusionMask)\b/,
      );
      expect(code).not.toMatch(/\.sort\s*\(|\.reduce\s*\(/);
    },
  );

  it("keeps the generated contract file recognisably generated", () => {
    const generated = read(GENERATED_FILE);
    expect(generated).toMatch(/auto-generated by openapi-typescript/);
    for (const path of [
      "/runs",
      "/runs/{run_id}/results",
      "/runs/{run_id}/sites/{cell_id}",
      "/runs/{run_id}/exclusions",
      "/scenario-comparison",
      "/data-quality",
    ]) {
      expect(generated).toContain(`"${path}"`);
    }
  });
});
