"""
Inspection stage — statistical summary of AEMO demand data.

Reads the consolidated half-hourly CSV and generates a comprehensive
inspection report covering dataset overview, column profiling, regional
statistics, temporal completeness, data quality, and monthly patterns.

Importable entry point:
    from pipelines.demand.inspect import run
    summary_path = run(csv_path=Path(...), output_dir=Path(...))

Standalone usage:
    python -m pipelines.demand.inspect path/to/file.csv

Output:
    inspection_summary.txt in the specified output directory.
"""

import argparse
import sys
from datetime import timedelta
from pathlib import Path

import pandas as pd

from . import config


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _write_section(f, title: str, content: str):
    """Write a titled section to the summary file."""
    separator = "=" * 70
    f.write(f"\n{separator}\n")
    f.write(f"  {title}\n")
    f.write(f"{separator}\n\n")
    f.write(content)
    f.write("\n")


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run(csv_path: Path, output_dir: Path, verbose: bool = False) -> Path:
    """
    Generate an inspection summary for the consolidated demand CSV.

    Parameters
    ----------
    csv_path : Path
        Path to the consolidated half-hourly CSV.
    output_dir : Path
        Directory where the inspection summary will be written.
    verbose : bool
        Print additional detail to console.

    Returns
    -------
    Path
        Path to the generated inspection summary file.
    """
    output_summary = output_dir / config.INSPECTION_SUMMARY_NAME

    print(f"  Input: {csv_path.name}")
    print(f"  Loading...")

    df = pd.read_csv(csv_path)
    df["INTERVAL_DATETIME"] = pd.to_datetime(df["INTERVAL_DATETIME"])

    file_size_mb = csv_path.stat().st_size / (1024 * 1024)

    print(f"  Loaded: {len(df):,} rows, {df.shape[1]} columns, {file_size_mb:.1f} MB")

    with open(output_summary, "w") as f:
        f.write("AEMO NEM OPERATIONAL DEMAND DATA — INSPECTION SUMMARY\n")
        f.write(f"Generated by: pipelines.demand.inspect\n")
        f.write(f"Input file: {csv_path.name}\n")
        f.write(f"File size: {file_size_mb:.2f} MB\n")

        # --- Section 1: Dataset Overview ---
        overview = []
        overview.append(f"Rows: {len(df):,}")
        overview.append(f"Columns: {df.shape[1]}")
        overview.append(f"Column names: {list(df.columns)}")
        overview.append(f"File size: {file_size_mb:.2f} MB")
        overview.append(
            f"Date range: {df['INTERVAL_DATETIME'].min()} to {df['INTERVAL_DATETIME'].max()}"
        )
        overview.append(f"Regions: {sorted(df['REGIONID'].unique())}")
        overview.append(f"Rows per region: {len(df) // df['REGIONID'].nunique():,}")

        # Temporal resolution
        sample_region = sorted(df["REGIONID"].unique())[0]
        region_sorted = (
            df[df["REGIONID"] == sample_region]
            .sort_values("INTERVAL_DATETIME")["INTERVAL_DATETIME"]
        )
        region_diffs = region_sorted.diff().dropna()
        most_common_interval = region_diffs.mode().iloc[0]
        overview.append(f"Temporal resolution: {most_common_interval} (most common interval)")
        overview.append(f"Time zone: NEM Time (AEST = UTC+10, no daylight saving adjustment)")

        _write_section(f, "DATASET OVERVIEW", "\n".join(overview))

        # --- Section 2: Column Profiling ---
        col_info = []
        col_info.append(
            f"{'Column':<35} {'Dtype':<15} {'Non-Null':<12} {'Null':<8} {'Unique':<10} {'Sample Value'}"
        )
        col_info.append("-" * 110)
        for col in df.columns:
            dtype = str(df[col].dtype)
            non_null = df[col].notna().sum()
            null_count = df[col].isna().sum()
            unique = df[col].nunique()
            sample = str(df[col].iloc[0])[:30]
            col_info.append(
                f"{col:<35} {dtype:<15} {non_null:<12} {null_count:<8} {unique:<10} {sample}"
            )

        _write_section(f, "COLUMN PROFILING", "\n".join(col_info))

        # --- Section 3: Regional Demand Statistics ---
        demand_stats = (
            df.groupby("REGIONID")["OPERATIONAL_DEMAND"]
            .agg(["count", "mean", "std", "min", "max"])
            .round(1)
        )
        demand_stats["25%"] = (
            df.groupby("REGIONID")["OPERATIONAL_DEMAND"].quantile(0.25).round(1)
        )
        demand_stats["50%"] = (
            df.groupby("REGIONID")["OPERATIONAL_DEMAND"].quantile(0.50).round(1)
        )
        demand_stats["75%"] = (
            df.groupby("REGIONID")["OPERATIONAL_DEMAND"].quantile(0.75).round(1)
        )

        region_content = []
        region_content.append("Operational Demand by NEM Region (MW)")
        region_content.append("")
        region_content.append(demand_stats.to_string())
        region_content.append("")
        region_content.append("Notes:")
        region_content.append("  - Units: MW (megawatts)")
        region_content.append(
            "  - 'Operational Demand' = demand met by scheduled, semi-scheduled"
        )
        region_content.append(
            "    and significant non-scheduled generation (excludes rooftop PV)"
        )
        region_content.append(
            "  - Negative values (e.g. SA1 min) occur when distributed"
        )
        region_content.append("    generation exceeds regional consumption")

        # Annual mean demand per region
        annual_mean = df.groupby("REGIONID")["OPERATIONAL_DEMAND"].mean().round(1)
        region_content.append("")
        region_content.append("Annual Mean Demand (MW) — suitable as regional demand indicator:")
        for region, mean_val in annual_mean.items():
            region_content.append(f"  {region}: {mean_val:,.1f} MW")

        _write_section(f, "REGIONAL DEMAND STATISTICS", "\n".join(region_content))

        # --- Section 4: Temporal Completeness ---
        temporal = []

        for region in sorted(df["REGIONID"].unique()):
            region_df = df[df["REGIONID"] == region].sort_values("INTERVAL_DATETIME")
            n_days = (
                region_df["INTERVAL_DATETIME"].max() - region_df["INTERVAL_DATETIME"].min()
            ).days
            expected_rows = n_days * 48  # 48 intervals per day for 30-min resolution
            actual_rows = len(region_df)
            completeness = (actual_rows / expected_rows * 100) if expected_rows > 0 else 0

            region_diffs = region_df["INTERVAL_DATETIME"].diff().dropna()
            gap_mask = region_diffs > timedelta(minutes=31)
            n_gaps = gap_mask.sum()

            temporal.append(f"{region}:")
            temporal.append(
                f"  Date range: {region_df['INTERVAL_DATETIME'].min()} "
                f"to {region_df['INTERVAL_DATETIME'].max()}"
            )
            temporal.append(f"  Rows: {actual_rows:,} (expected ~{expected_rows:,})")
            temporal.append(f"  Completeness: {completeness:.1f}%")
            temporal.append(f"  Gaps (>30min): {n_gaps}")
            temporal.append("")

        _write_section(f, "TEMPORAL COMPLETENESS", "\n".join(temporal))

        # --- Section 5: Data Quality Checks ---
        quality = []

        n_dupes = df.duplicated(subset=["REGIONID", "INTERVAL_DATETIME"]).sum()
        quality.append(f"Duplicate rows (same region + timestamp): {n_dupes}")

        quality.append("Missing values per column:")
        for col in df.columns:
            n_missing = df[col].isna().sum()
            quality.append(f"  {col}: {n_missing}")

        neg_demand = df[df["OPERATIONAL_DEMAND"] < 0]
        quality.append(f"\nNegative demand values: {len(neg_demand)} rows")
        if len(neg_demand) > 0:
            quality.append(
                f"  Regions with negative demand: {sorted(neg_demand['REGIONID'].unique())}"
            )
            quality.append(f"  Most negative: {neg_demand['OPERATIONAL_DEMAND'].min()} MW")
            quality.append(
                "  (Expected: occurs in SA when distributed solar exceeds load)"
            )

        # Extreme values
        for region in sorted(df["REGIONID"].unique()):
            region_df = df[df["REGIONID"] == region]
            q99 = region_df["OPERATIONAL_DEMAND"].quantile(0.99)
            extreme = region_df[region_df["OPERATIONAL_DEMAND"] > q99 * 1.5]
            if len(extreme) > 0:
                quality.append(
                    f"  {region}: {len(extreme)} values > 1.5x P99 ({q99:.0f} MW)"
                )

        # Adjustment and WDR columns
        if "OPERATIONAL_DEMAND_ADJUSTMENT" in df.columns:
            quality.append(
                f"\nOPERATIONAL_DEMAND_ADJUSTMENT: all zeros = "
                f"{(df['OPERATIONAL_DEMAND_ADJUSTMENT'] == 0).all()}"
            )
        if "WDR_ESTIMATE" in df.columns:
            quality.append(
                f"WDR_ESTIMATE: all zeros = {(df['WDR_ESTIMATE'] == 0).all()}"
            )

        _write_section(f, "DATA QUALITY CHECKS", "\n".join(quality))

        # --- Section 6: Monthly Patterns ---
        monthly_content = []
        monthly_content.append("Monthly Mean Demand by Region (MW):")
        monthly_content.append("")

        monthly_mean_pivot = df.pivot_table(
            values="OPERATIONAL_DEMAND",
            index=df["INTERVAL_DATETIME"].dt.to_period("M"),
            columns="REGIONID",
            aggfunc="mean",
        ).round(0)
        monthly_content.append(monthly_mean_pivot.to_string())

        monthly_content.append("")
        monthly_content.append("Monthly Max Demand by Region (MW):")
        monthly_content.append("")
        monthly_max_pivot = df.pivot_table(
            values="OPERATIONAL_DEMAND",
            index=df["INTERVAL_DATETIME"].dt.to_period("M"),
            columns="REGIONID",
            aggfunc="max",
        ).round(0)
        monthly_content.append(monthly_max_pivot.to_string())

        _write_section(f, "MONTHLY PATTERNS", "\n".join(monthly_content))

        # --- Section 7: Data Dictionary ---
        dictionary = []
        dictionary.append("Dataset: AEMO NEM Operational Demand (Actual, Half-Hourly)")
        dictionary.append(
            "Source: nemweb.com.au/Reports/Archive/Operational_Demand/ACTUAL_DAILY/"
        )
        dictionary.append("Format: CSV (extracted from nested ZIPs)")
        dictionary.append("CRS: N/A (tabular, region-level)")
        dictionary.append(
            f"Temporal Range: {df['INTERVAL_DATETIME'].min()} to {df['INTERVAL_DATETIME'].max()}"
        )
        dictionary.append("Temporal Resolution: 30 minutes (half-hourly)")
        dictionary.append("Spatial Resolution: NEM Region (NSW1, QLD1, SA1, TAS1, VIC1)")
        dictionary.append("Time Zone: NEM Time (AEST = UTC+10, no daylight saving)")
        dictionary.append("")
        dictionary.append(
            f"{'Field':<35} {'Type':<12} {'Units':<8} {'Description':<40} {'Example'}"
        )
        dictionary.append("-" * 120)
        dictionary.append(
            f"{'REGIONID':<35} {'string':<12} {'—':<8} {'NEM region identifier':<40} NSW1"
        )
        dictionary.append(
            f"{'INTERVAL_DATETIME':<35} {'datetime':<12} {'—':<8} "
            f"{'End of 30-min dispatch interval':<40} 2025-07-01 04:30:00"
        )
        dictionary.append(
            f"{'OPERATIONAL_DEMAND':<35} {'integer':<12} {'MW':<8} "
            f"{'Regional operational demand':<40} 7604"
        )
        dictionary.append(
            f"{'OPERATIONAL_DEMAND_ADJUSTMENT':<35} {'integer':<12} {'MW':<8} "
            f"{'Demand adjustment (usually 0)':<40} 0"
        )
        dictionary.append(
            f"{'WDR_ESTIMATE':<35} {'integer':<12} {'MW':<8} "
            f"{'Wholesale demand response estimate':<40} 0"
        )
        dictionary.append(
            f"{'LASTCHANGED':<35} {'datetime':<12} {'—':<8} "
            f"{'Timestamp of last data update':<40} 2025-07-01 04:30:02"
        )

        _write_section(f, "DATA DICTIONARY", "\n".join(dictionary))

    print(f"  Summary written: {output_summary.name}")

    # Console key findings
    n_neg = len(neg_demand)
    print(f"\n  Key findings:")
    print(f"    {len(df):,} rows, {df.shape[1]} columns, {file_size_mb:.1f} MB")
    print(f"    {df['REGIONID'].nunique()} NEM regions, 30-min resolution")
    print(
        f"    Date range: {df['INTERVAL_DATETIME'].min()} to {df['INTERVAL_DATETIME'].max()}"
    )
    print(f"    {n_dupes} duplicates, {n_neg} negative demand values")

    return output_summary


# ---------------------------------------------------------------------------
# Standalone execution
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate inspection summary for AEMO demand data."
    )
    parser.add_argument("input_csv", type=str, help="Path to consolidated CSV.")
    parser.add_argument("--output-dir", type=str, default=None)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    input_path = Path(args.input_csv)
    if not input_path.exists():
        print(f"ERROR: File not found: {input_path}")
        sys.exit(1)

    out_dir = Path(args.output_dir) if args.output_dir else input_path.parent
    summary = run(csv_path=input_path, output_dir=out_dir, verbose=args.verbose)
    print(f"\nDone. Summary: {summary}")
