"""
Inspect AEMO NEM Operational Demand data sample.

Reads a consolidated CSV (produced by download_aemo_demand.py) and generates
a comprehensive inspection summary covering:
  - Dataset overview (shape, file size, date range)
  - Column profiling (types, nulls, unique values)
  - Regional demand statistics (mean, min, max, std by region)
  - Temporal analysis (resolution, gaps, completeness)
  - Data quality checks (negatives, outliers, duplicates)
  - Monthly/seasonal patterns

Usage:
  python inspect_demand_data.py aemo_operational_demand_20250701_20260630.csv
  python inspect_demand_data.py  # auto-detects most recent aemo_operational_demand_*.csv

Output:
  - Console summary
  - inspection_summary_<start>_<end>.txt (alongside input file)

Source data: Output of download_aemo_demand.py
"""

import argparse
import glob
import os
import re
import sys
from datetime import timedelta
from pathlib import Path

import pandas as pd

# --- Configuration ---
BASE_DIR = Path(__file__).resolve().parent


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Inspect AEMO NEM Operational Demand data and generate summary.",
        epilog=(
            "Example:\n"
            "  python inspect_demand_data.py aemo_operational_demand_20250701_20260630.csv\n"
            "  python inspect_demand_data.py  # auto-detects most recent file"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "input_csv",
        nargs="?",
        default=None,
        help=(
            "Path to the consolidated CSV file to inspect. "
            "If not provided, auto-detects the most recent aemo_operational_demand_*.csv "
            "in the script directory."
        ),
    )
    return parser.parse_args()


def find_latest_csv() -> Path | None:
    """Find the most recent aemo_operational_demand_*.csv in BASE_DIR."""
    pattern = str(BASE_DIR / "aemo_operational_demand_*.csv")
    matches = sorted(glob.glob(pattern))
    if matches:
        return Path(matches[-1])
    return None


def get_output_summary_path(input_csv: Path) -> Path:
    """Generate the output summary path based on the input filename."""
    # Try to extract date range from filename
    match = re.search(r'(\d{8})_(\d{8})', input_csv.stem)
    if match:
        return input_csv.parent / f"inspection_summary_{match.group(1)}_{match.group(2)}.txt"
    # Fallback: use input stem
    return input_csv.parent / f"inspection_summary.txt"


def write_section(f, title: str, content: str):
    """Write a titled section to the summary file."""
    separator = "=" * 70
    f.write(f"\n{separator}\n")
    f.write(f"  {title}\n")
    f.write(f"{separator}\n\n")
    f.write(content)
    f.write("\n")


def main():
    """Run the full inspection pipeline."""
    args = parse_args()

    # Resolve input CSV
    if args.input_csv:
        input_csv = Path(args.input_csv)
        if not input_csv.is_absolute():
            input_csv = Path.cwd() / input_csv
    else:
        input_csv = find_latest_csv()
        if input_csv is None:
            print("ERROR: No input file specified and no aemo_operational_demand_*.csv found.")
            print("Usage: python inspect_demand_data.py <path_to_csv>")
            sys.exit(1)
        print(f"Auto-detected input: {input_csv.name}")

    if not input_csv.exists():
        print(f"ERROR: Input file not found: {input_csv}")
        print("Run download_aemo_demand.py first.")
        sys.exit(1)

    output_summary = get_output_summary_path(input_csv)

    # Load data
    print(f"Loading {input_csv}...")
    df = pd.read_csv(input_csv)
    df['INTERVAL_DATETIME'] = pd.to_datetime(df['INTERVAL_DATETIME'])

    file_size_mb = input_csv.stat().st_size / (1024 * 1024)

    # Open output file
    with open(output_summary, 'w') as f:
        f.write("AEMO NEM OPERATIONAL DEMAND DATA — INSPECTION SUMMARY\n")
        f.write(f"Generated by: inspect_demand_data.py\n")
        f.write(f"Input file: {input_csv.name}\n")
        f.write(f"File size: {file_size_mb:.2f} MB\n")

        # --- Section 1: Dataset Overview ---
        overview = []
        overview.append(f"Rows: {len(df):,}")
        overview.append(f"Columns: {df.shape[1]}")
        overview.append(f"Column names: {list(df.columns)}")
        overview.append(f"File size: {file_size_mb:.2f} MB")
        overview.append(f"Date range: {df['INTERVAL_DATETIME'].min()} to {df['INTERVAL_DATETIME'].max()}")
        overview.append(f"Regions: {sorted(df['REGIONID'].unique())}")
        overview.append(f"Rows per region: {len(df) // df['REGIONID'].nunique():,}")

        # Temporal resolution (computed per single region to avoid cross-region zero diffs)
        sample_region = sorted(df['REGIONID'].unique())[0]
        region_sorted = df[df['REGIONID'] == sample_region].sort_values('INTERVAL_DATETIME')['INTERVAL_DATETIME']
        region_diffs = region_sorted.diff().dropna()
        most_common_interval = region_diffs.mode().iloc[0]
        overview.append(f"Temporal resolution: {most_common_interval} (most common interval)")
        overview.append(f"Time zone: NEM Time (AEST = UTC+10, no daylight saving adjustment)")

        write_section(f, "DATASET OVERVIEW", "\n".join(overview))

        # --- Section 2: Column Profiling ---
        col_info = []
        col_info.append(f"{'Column':<35} {'Dtype':<15} {'Non-Null':<12} {'Null':<8} {'Unique':<10} {'Sample Value'}")
        col_info.append("-" * 110)
        for col in df.columns:
            dtype = str(df[col].dtype)
            non_null = df[col].notna().sum()
            null_count = df[col].isna().sum()
            unique = df[col].nunique()
            sample = str(df[col].iloc[0])[:30]
            col_info.append(f"{col:<35} {dtype:<15} {non_null:<12} {null_count:<8} {unique:<10} {sample}")

        write_section(f, "COLUMN PROFILING", "\n".join(col_info))

        # --- Section 3: Regional Demand Statistics ---
        demand_stats = df.groupby('REGIONID')['OPERATIONAL_DEMAND'].agg([
            'count', 'mean', 'std', 'min', 'max'
        ]).round(1)
        demand_stats['25%'] = df.groupby('REGIONID')['OPERATIONAL_DEMAND'].quantile(0.25).round(1)
        demand_stats['50%'] = df.groupby('REGIONID')['OPERATIONAL_DEMAND'].quantile(0.50).round(1)
        demand_stats['75%'] = df.groupby('REGIONID')['OPERATIONAL_DEMAND'].quantile(0.75).round(1)

        region_content = []
        region_content.append("Operational Demand by NEM Region (MW)")
        region_content.append("")
        region_content.append(demand_stats.to_string())
        region_content.append("")
        region_content.append("Notes:")
        region_content.append("  - Units: MW (megawatts)")
        region_content.append("  - 'Operational Demand' = demand met by scheduled, semi-scheduled")
        region_content.append("    and significant non-scheduled generation (excludes rooftop PV)")
        region_content.append("  - Negative values (e.g. SA1 min=-263) occur when distributed")
        region_content.append("    generation exceeds regional consumption")

        # Annual mean demand per region (useful for the platform)
        annual_mean = df.groupby('REGIONID')['OPERATIONAL_DEMAND'].mean().round(1)
        region_content.append("")
        region_content.append("Annual Mean Demand (MW) — suitable as regional demand indicator:")
        for region, mean_val in annual_mean.items():
            region_content.append(f"  {region}: {mean_val:,.1f} MW")

        write_section(f, "REGIONAL DEMAND STATISTICS", "\n".join(region_content))

        # --- Section 4: Temporal Completeness ---
        temporal = []

        for region in sorted(df['REGIONID'].unique()):
            region_df = df[df['REGIONID'] == region].sort_values('INTERVAL_DATETIME')
            expected_intervals = 48  # per day for 30-min resolution
            n_days = (region_df['INTERVAL_DATETIME'].max() - region_df['INTERVAL_DATETIME'].min()).days
            expected_rows = n_days * expected_intervals
            actual_rows = len(region_df)
            completeness = (actual_rows / expected_rows * 100) if expected_rows > 0 else 0

            # Check for gaps
            region_diffs = region_df['INTERVAL_DATETIME'].diff().dropna()
            gap_mask = region_diffs > timedelta(minutes=31)
            n_gaps = gap_mask.sum()

            temporal.append(f"{region}:")
            temporal.append(f"  Date range: {region_df['INTERVAL_DATETIME'].min()} to {region_df['INTERVAL_DATETIME'].max()}")
            temporal.append(f"  Rows: {actual_rows:,} (expected ~{expected_rows:,})")
            temporal.append(f"  Completeness: {completeness:.1f}%")
            temporal.append(f"  Gaps (>30min): {n_gaps}")
            temporal.append("")

        write_section(f, "TEMPORAL COMPLETENESS", "\n".join(temporal))

        # --- Section 5: Data Quality Checks ---
        quality = []

        # Duplicates
        n_dupes = df.duplicated(subset=['REGIONID', 'INTERVAL_DATETIME']).sum()
        quality.append(f"Duplicate rows (same region + timestamp): {n_dupes}")

        # Missing values
        quality.append(f"Missing values per column:")
        for col in df.columns:
            n_missing = df[col].isna().sum()
            quality.append(f"  {col}: {n_missing}")

        # Negative demand
        neg_demand = df[df['OPERATIONAL_DEMAND'] < 0]
        quality.append(f"\nNegative demand values: {len(neg_demand)} rows")
        if len(neg_demand) > 0:
            quality.append(f"  Regions with negative demand: {sorted(neg_demand['REGIONID'].unique())}")
            quality.append(f"  Most negative: {neg_demand['OPERATIONAL_DEMAND'].min()} MW")
            quality.append("  (Expected: occurs in SA when distributed solar exceeds load)")

        # Very high demand (potential outliers)
        for region in sorted(df['REGIONID'].unique()):
            region_df = df[df['REGIONID'] == region]
            q99 = region_df['OPERATIONAL_DEMAND'].quantile(0.99)
            extreme = region_df[region_df['OPERATIONAL_DEMAND'] > q99 * 1.5]
            if len(extreme) > 0:
                quality.append(f"  {region}: {len(extreme)} values > 1.5x P99 ({q99:.0f} MW)")

        # WDR and adjustment columns
        quality.append(f"\nOPERATIONAL_DEMAND_ADJUSTMENT: all zeros = {(df['OPERATIONAL_DEMAND_ADJUSTMENT'] == 0).all()}")
        quality.append(f"WDR_ESTIMATE: all zeros = {(df['WDR_ESTIMATE'] == 0).all()}")

        write_section(f, "DATA QUALITY CHECKS", "\n".join(quality))

        # --- Section 6: Monthly Patterns ---
        df['month'] = df['INTERVAL_DATETIME'].dt.to_period('M')

        monthly_content = []
        monthly_content.append("Monthly Mean Demand by Region (MW):")
        monthly_content.append("")

        monthly_mean_pivot = df.pivot_table(
            values='OPERATIONAL_DEMAND',
            index=df['INTERVAL_DATETIME'].dt.to_period('M'),
            columns='REGIONID',
            aggfunc='mean'
        ).round(0)
        monthly_content.append(monthly_mean_pivot.to_string())

        monthly_content.append("")
        monthly_content.append("Monthly Max Demand by Region (MW):")
        monthly_content.append("")
        monthly_max_pivot = df.pivot_table(
            values='OPERATIONAL_DEMAND',
            index=df['INTERVAL_DATETIME'].dt.to_period('M'),
            columns='REGIONID',
            aggfunc='max'
        ).round(0)
        monthly_content.append(monthly_max_pivot.to_string())

        write_section(f, "MONTHLY PATTERNS", "\n".join(monthly_content))

        # --- Section 7: Data Dictionary ---
        dictionary = []
        dictionary.append("Dataset: AEMO NEM Operational Demand (Actual, Half-Hourly)")
        dictionary.append(f"Source: nemweb.com.au/Reports/Archive/Operational_Demand/ACTUAL_DAILY/")
        dictionary.append(f"Format: CSV (extracted from nested ZIPs)")
        dictionary.append(f"CRS: N/A (tabular, region-level)")
        dictionary.append(f"Temporal Range: {df['INTERVAL_DATETIME'].min()} to {df['INTERVAL_DATETIME'].max()}")
        dictionary.append(f"Temporal Resolution: 30 minutes (half-hourly)")
        dictionary.append(f"Spatial Resolution: NEM Region (NSW1, QLD1, SA1, TAS1, VIC1)")
        dictionary.append(f"Time Zone: NEM Time (AEST = UTC+10, no daylight saving)")
        dictionary.append("")
        dictionary.append(f"{'Field':<35} {'Type':<12} {'Units':<8} {'Description':<40} {'Example'}")
        dictionary.append("-" * 120)
        dictionary.append(f"{'REGIONID':<35} {'string':<12} {'—':<8} {'NEM region identifier':<40} NSW1")
        dictionary.append(f"{'INTERVAL_DATETIME':<35} {'datetime':<12} {'—':<8} {'End of 30-min dispatch interval':<40} 2025-07-01 04:30:00")
        dictionary.append(f"{'OPERATIONAL_DEMAND':<35} {'integer':<12} {'MW':<8} {'Regional operational demand':<40} 7604")
        dictionary.append(f"{'OPERATIONAL_DEMAND_ADJUSTMENT':<35} {'integer':<12} {'MW':<8} {'Demand adjustment (usually 0)':<40} 0")
        dictionary.append(f"{'WDR_ESTIMATE':<35} {'integer':<12} {'MW':<8} {'Wholesale demand response estimate':<40} 0")
        dictionary.append(f"{'LASTCHANGED':<35} {'datetime':<12} {'—':<8} {'Timestamp of last data update':<40} 2025-07-01 04:30:02")

        write_section(f, "DATA DICTIONARY", "\n".join(dictionary))

        # --- Section 8: Recommendations for Platform ---
        recs = []
        recs.append("1. RECOMMENDED DATASET: AEMO Operational Demand (Actual, Half-Hourly)")
        recs.append("   - Most appropriate metric: OPERATIONAL_DEMAND (MW)")
        recs.append("   - Represents demand met by scheduled/semi-scheduled generation")
        recs.append("   - Available at 30-minute resolution, freely downloadable")
        recs.append("")
        recs.append("2. RECOMMENDED TEMPORAL AGGREGATION:")
        recs.append("   - Annual mean demand per region (primary indicator)")
        recs.append("   - Also compute: peak demand, seasonal variation")
        recs.append("   - For the screening model, annual mean is sufficient")
        recs.append("")
        recs.append("3. EXTENSIBILITY:")
        recs.append("   - Pipeline supports configurable date ranges (--start-date / --end-date)")
        recs.append("   - Target: extend to 3-5 recent complete years for robust demand indicator")
        recs.append("   - Archive contains monthly ZIPs going further back")
        recs.append("")
        recs.append("4. SPATIAL ALLOCATION (deferred to Task 5):")
        recs.append("   - Data is at NEM region level, not per grid cell")
        recs.append("   - Requires population-weighted or load-centre proxy")
        recs.append("   - Cell-level values are ESTIMATED/PROXY demand, not actual consumption")
        recs.append("   - The demand indicator for a cell = f(regional_demand, allocation_weight)")
        recs.append("")
        recs.append("5. COVERAGE GAP:")
        recs.append("   - NEM does not cover Western Australia (SWIS) or Northern Territory")
        recs.append("   - WA has separate operator (AEMO WA / WEM)")
        recs.append("   - NT has separate operator (Territory Generation / Power & Water)")
        recs.append("   - Documented as a platform limitation for the MVP")
        recs.append("")
        recs.append("6. DATA PROVENANCE:")
        recs.append("   - See DATA_PROVENANCE.md for full provenance, licence, and limitations")

        write_section(f, "RECOMMENDATIONS FOR PLATFORM", "\n".join(recs))

    print(f"\nInspection complete. Summary saved to:\n  {output_summary}")
    print(f"\nKey findings:")
    print(f"  - {len(df):,} rows, {df.shape[1]} columns")
    print(f"  - {df['REGIONID'].nunique()} NEM regions, 30-min resolution, {file_size_mb:.1f} MB")
    print(f"  - Date range: {df['INTERVAL_DATETIME'].min()} to {df['INTERVAL_DATETIME'].max()}")
    print(f"  - Zero missing values, {n_dupes} duplicates")
    print(f"  - {len(neg_demand)} negative demand values (SA1 solar exports)")
    print(f"  - Recommended metric: Annual mean OPERATIONAL_DEMAND per region")


if __name__ == "__main__":
    main()
