/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Data Quality
         * @description `get_data_quality` — the frozen dataset's S2-02 Data_Quality_Status.
         */
        get: operations["read_data_quality_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description `run_analysis` — materialise a Run under the given weights or scenario.
         *
         *     Passes `weights` / `scenario` straight to the operation; the engine parser
         *     is the single validator (CONTRACT.md §3, §5). No one-of check or weight
         *     interpretation is done here.
         */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Exclusions
         * @description `get_exclusions` — the Run's excluded cells with their reasons.
         */
        get: operations["read_exclusions_runs__run_id__exclusions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Ranked Results
         * @description `get_ranked_results` — the Run's ranked rows, optionally display-filtered.
         *
         *     `top_n` / `min_score` are passed straight through to the operation, which
         *     owns the pure display-selection (CONTRACT.md §4.2). This layer never
         *     re-scores, re-ranks, or thresholds.
         */
        get: operations["read_ranked_results_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/sites/{cell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Site Detail
         * @description `get_site_detail` — one cell's full detail for a Run.
         */
        get: operations["read_site_detail_runs__run_id__sites__cell_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Scenario Comparison
         * @description `compare_scenarios` — per-cell rank comparison of two named scenarios.
         */
        post: operations["create_scenario_comparison_scenario_comparison_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Criterion
         * @description One scored criterion inside a `Weights` configuration (CONTRACT.md §5).
         *
         *     Mirrors the `scoring_weights.yaml` / scenario `criteria` entry so it is
         *     validated by the SAME engine parser (`pipeline/scoring/weights.py`), never a
         *     duplicate validator — hence no field constraints (e.g. weight >= 0, the
         *     direction enum) are re-declared here.
         */
        Criterion: {
            /** Direction */
            direction: string;
            /** Feature */
            feature: string;
            /** Rationale */
            rationale: string;
            /** Weight */
            weight: number;
        };
        /**
         * DataQualityCheck
         * @description One data-quality check record (CONTRACT.md §5, S2-02 shape).
         */
        DataQualityCheck: {
            /** Expected */
            expected: string;
            /** Name */
            name: string;
            /** Observed */
            observed: string;
            /** Passed */
            passed: boolean;
        };
        /**
         * DataQualityStatus
         * @description The S2-02 Data_Quality_Status for the frozen integrated dataset (CONTRACT.md §5).
         */
        DataQualityStatus: {
            /** Checks */
            checks?: components["schemas"]["DataQualityCheck"][];
            /**
             * Passed
             * @default false
             */
            passed: boolean;
        };
        /**
         * ExcludedRow
         * @description One excluded cell's eligibility reason(s) for a Run (CONTRACT.md §5).
         */
        ExcludedRow: {
            /** Cell Id */
            cell_id: string;
            /** Reason Codes */
            reason_codes?: string[];
            /**
             * Reason Text
             * @default
             */
            reason_text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RankedRow
         * @description One eligible cell's ranked result for a Run (CONTRACT.md §5).
         */
        RankedRow: {
            /** Cell Id */
            cell_id: string;
            /** Key Components */
            key_components?: {
                [key: string]: number;
            };
            /** Rank */
            rank: number;
            /** Suitability Score */
            suitability_score: number;
        };
        /**
         * RunHandle
         * @description Identifies one materialised Run (CONTRACT.md §5).
         */
        RunHandle: {
            /** Run Id */
            run_id: string;
            /** Scenario */
            scenario?: string | null;
            /** Weights Id */
            weights_id: string;
        };
        /**
         * RunRequest
         * @description Request body for `run_analysis` — `POST /runs` (CONTRACT.md §4.1, §5).
         *
         *     Exactly one of `weights` / `scenario` must be given; that one-of rule is
         *     enforced by the `run_analysis` operation (which returns 422 on a fault),
         *     not by this model, so both fields are nullable here. The backend does NOT
         *     validate weights itself — it passes them to the engine parser.
         */
        RunRequest: {
            /** Scenario */
            scenario?: string | null;
            weights?: components["schemas"]["Weights"] | null;
        };
        /**
         * ScenarioComparison
         * @description A per-cell ranking comparison between two scenarios (CONTRACT.md §5).
         */
        ScenarioComparison: {
            /** Labels */
            labels?: {
                [key: string]: string;
            };
            /** Rows */
            rows?: components["schemas"]["ScenarioComparisonRow"][];
        };
        /**
         * ScenarioComparisonRequest
         * @description Request body for `compare_scenarios` — `POST /scenario-comparison`
         *     (CONTRACT.md §4.5, §5). Both scenario keys are required.
         */
        ScenarioComparisonRequest: {
            /** Scenario A */
            scenario_a: string;
            /** Scenario B */
            scenario_b: string;
        };
        /**
         * ScenarioComparisonRow
         * @description One cell's rank comparison across two scenarios (CONTRACT.md §5).
         */
        ScenarioComparisonRow: {
            /** Cell Id */
            cell_id: string;
            /** Rank A */
            rank_a?: number | null;
            /** Rank B */
            rank_b?: number | null;
            /** Rank Delta */
            rank_delta?: number | null;
        };
        /**
         * SiteDetail
         * @description One cell's full detail for a Run (CONTRACT.md §5).
         *
         *     `explanation` carries the S2-06 `Explanation_Structure` verbatim (the
         *     eligible-path or excluded-path record exactly as S2-06 wrote it); it is a
         *     free-form mapping so the mirror neither renames nor reorders S2-06's fields.
         */
        SiteDetail: {
            /** Cell Id */
            cell_id: string;
            /** Contributions */
            contributions?: {
                [key: string]: number;
            };
            /**
             * Eligible
             * @default false
             */
            eligible: boolean;
            /** Explanation */
            explanation?: Record<string, unknown>;
            /** Features */
            features?: Record<string, unknown>;
            /** Rank */
            rank?: number | null;
            /** Suitability Score */
            suitability_score?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Weights
         * @description Explicit weights configuration for `run_analysis` (CONTRACT.md §5).
         *
         *     Mirrors the `scoring_weights.yaml` / scenario `criteria` structure so it is
         *     validated by the same engine parser, never a duplicate validator.
         */
        Weights: {
            /** Criteria */
            criteria?: components["schemas"]["Criterion"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_data_quality_data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityStatus"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHandle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_exclusions_runs__run_id__exclusions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcludedRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_ranked_results_runs__run_id__results_get: {
        parameters: {
            query?: {
                top_n?: number | null;
                min_score?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankedRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_site_detail_runs__run_id__sites__cell_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scenario_comparison_scenario_comparison_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
