"""
Infrastructure inspect stage — examine substations, power lines, generators.

Reads the pre-downloaded GA Electricity Infrastructure GeoJSON files,
filters by state/fuel, writes filtered subsets, and produces inspection
reports with statistics and an SVG preview for power lines.

Importable entry point:
    from pipeline.infrastructure.inspect import run
    result = run(verbose=False, state="NSW", fuel_type="wind")

Output:
    DATA/infrastructure/metadata/ga_substations_2026_inspection.md
    DATA/infrastructure/metadata/ga_power_lines_2026_inspection.md
    DATA/infrastructure/metadata/ga_power_lines_2026_preview.svg
    DATA/infrastructure/metadata/ga_generators_2026_inspection.md
"""

from __future__ import annotations

from pathlib import Path

from . import config
from .helpers import (
    compute_bounds,
    compute_field_stats,
    count_geometry_types,
    count_property,
    count_valid_coordinates,
    filter_by_fuel_type,
    filter_by_state,
    load_geojson,
    write_geojson,
)
from ..common.geo import utc_now


# ---------------------------------------------------------------------------
# Substations
# ---------------------------------------------------------------------------


def _inspect_substations(state: str, verbose: bool = False) -> Path:
    """Inspect GA substations and create state subset."""
    source_path = config.INFRA_DIR / "substations" / "ga_substations_2026_australia.geojson"
    collection = load_geojson(source_path)
    features = collection["features"]

    state_features = filter_by_state(features, state)
    state_label = state.lower() if state.upper() != "ALL" else "all"

    # Write filtered subset
    output_dir = config.INFRA_DIR / "substations"
    state_path = output_dir / f"ga_substations_2026_{state_label}.geojson"
    state_collection = {
        **collection,
        "name": f"Geoscience Australia Substations 2026 — {state.upper()}",
        "features": state_features,
    }
    write_geojson(state_path, state_collection)

    # Stats
    field_info = compute_field_stats(features)
    geometry_types = count_geometry_types(features)
    states = count_property(features, "state")
    statuses = count_property(features, "status")
    voltages = count_property(features, "voltage_kv")
    valid_coords = count_valid_coordinates(features)

    report = f"""# Geoscience Australia Substations 2026 — Inspection

*Generated by `pipeline.infrastructure.inspect` on {utc_now()}. Do not edit by hand.*

- Source: `https://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer/0`
- Custodian: Geoscience Australia
- Attribution: (c) Commonwealth of Australia (Geoscience Australia) 2026
- Format: ArcGIS Feature Service downloaded as GeoJSON
- CRS: EPSG:7844 (GDA2020)
- National feature count: {len(features)}
- State filter: {state.upper()}
- Filtered feature count: {len(state_features)}
- Geometry types: {dict(geometry_types)}
- Valid point coordinates: {valid_coords}/{len(features)}
- States: {states}
- Operational status values: {statuses}
- Voltage kV values: {dict(sorted(voltages.items()))}
- Missing values by field: {field_info['missing']}

## Fields

{', '.join(field_info['fields'])}

## Initial assessment

This dataset is suitable for screening-level proximity to transmission
substations. It provides point coordinates, voltage, state, locality, status and
spatial-confidence fields. It is not a complete engineering connection-capacity
register: a substation's voltage does not equal spare connection capacity.
"""
    report_path = config.INFRA_META_DIR / "ga_substations_2026_inspection.md"
    config.INFRA_META_DIR.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding="utf-8")
    if verbose:
        print(f"      Substations: {len(state_features)} filtered ({state.upper()})")
    return report_path


# ---------------------------------------------------------------------------
# Power lines
# ---------------------------------------------------------------------------


def _generate_power_lines_svg(
    features: list[dict], bounds: list[float], out_path: Path,
    width: int = 1000, height: int = 760, margin: int = 35,
    stroke_thin: float = 0.55, stroke_thick: float = 0.9,
    voltage_threshold: int = 220,
) -> None:
    """Generate an SVG preview map of power lines coloured by voltage."""
    min_x, min_y, max_x, max_y = bounds
    scale = min(
        (width - 2 * margin) / (max_x - min_x),
        (height - 2 * margin) / (max_y - min_y),
    )
    voltage_colours = {
        500: "#7f0000", 400: "#b30000", 330: "#d7301f", 275: "#ef6548",
        220: "#fc8d59", 132: "#3182bd", 110: "#6baed6", 88: "#9ecae1", 66: "#c6dbef",
    }

    def project(x, y):
        px = margin + (x - min_x) * scale
        py = height - margin - (y - min_y) * scale
        return px, py

    paths = []
    for feature in sorted(features, key=lambda f: int(f["properties"].get("capacity_kv") or 0)):
        voltage = int(feature["properties"].get("capacity_kv") or 0)
        colour = voltage_colours.get(voltage, "#999999")
        coords = feature["geometry"]["coordinates"]
        points = [project(x, y) for x, y in coords]
        path_data = " ".join(
            ("M" if i == 0 else "L") + f"{x:.2f},{y:.2f}"
            for i, (x, y) in enumerate(points)
        )
        sw = stroke_thin if voltage < voltage_threshold else stroke_thick
        paths.append(
            f'<path d="{path_data}" fill="none" stroke="{colour}" '
            f'stroke-width="{sw}" stroke-linecap="round"/>'
        )

    legend_items = []
    for i, voltage in enumerate(sorted(voltage_colours, reverse=True)):
        y = 80 + i * 24
        legend_items.append(
            f'<line x1="790" y1="{y}" x2="825" y2="{y}" '
            f'stroke="{voltage_colours[voltage]}" stroke-width="3"/>'
            f'<text x="835" y="{y + 5}" font-size="15">{voltage} kV</text>'
        )

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
<rect width="100%" height="100%" fill="white"/>
<text x="35" y="30" font-family="sans-serif" font-size="22" font-weight="bold">Geoscience Australia Power Lines 2026</text>
<text x="35" y="53" font-family="sans-serif" font-size="14">{len(features)} national features; colour represents nominal voltage</text>
<g>{''.join(paths)}</g>
<rect x="770" y="55" width="180" height="250" rx="6" fill="white" fill-opacity="0.9" stroke="#cccccc"/>
<g font-family="sans-serif">{''.join(legend_items)}</g>
</svg>"""
    out_path.write_text(svg, encoding="utf-8")


def _inspect_power_lines(state: str, verbose: bool = False) -> tuple[Path, Path]:
    """Inspect GA power lines: merge parts, filter, report + SVG preview."""
    parts = [
        config.INFRA_DIR / "transmission-lines" / "ga_power_lines_2026_part_001.geojson",
        config.INFRA_DIR / "transmission-lines" / "ga_power_lines_2026_part_002.geojson",
    ]
    collections = [load_geojson(p) for p in parts]
    features = [f for c in collections for f in c["features"]]
    object_ids = [f["properties"].get("objectid") for f in features]
    if len(object_ids) != len(set(object_ids)):
        raise RuntimeError("Duplicate OBJECTID values found across downloaded pages")

    output_dir = config.INFRA_DIR / "transmission-lines"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Write merged national file
    merged = {
        "type": "FeatureCollection",
        "name": "Geoscience Australia Power Lines 2026",
        "crs": collections[0].get("crs"),
        "features": features,
    }
    merged_path = output_dir / "ga_power_lines_2026_australia.geojson"
    write_geojson(merged_path, merged)

    # State filter
    state_features = filter_by_state(features, state)
    state_label = state.lower() if state.upper() != "ALL" else "all"
    state_path = output_dir / f"ga_power_lines_2026_{state_label}.geojson"
    state_collection = {
        **merged,
        "name": f"Geoscience Australia Power Lines 2026 — {state.upper()}",
        "features": state_features,
    }
    write_geojson(state_path, state_collection)

    # Stats
    field_info = compute_field_stats(features)
    geometry_counts = count_geometry_types(features)
    states = count_property(features, "state")
    statuses = count_property(features, "status")
    capacities = count_property(features, "capacity_kv")
    bounds = compute_bounds(features)

    report = f"""# Geoscience Australia Power Lines 2026 — Inspection

*Generated by `pipeline.infrastructure.inspect` on {utc_now()}. Do not edit by hand.*

- Source: `https://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer/2`
- Custodian: Geoscience Australia
- Attribution: (c) Commonwealth of Australia (Geoscience Australia) 2026
- Format: ArcGIS Feature Service downloaded as GeoJSON
- CRS: EPSG:7844 (GDA2020)
- National feature count: {len(features)}
- State filter applied: {state.upper()}
- Filtered feature count: {len(state_features)}
- Duplicate OBJECTIDs: {len(object_ids) - len(set(object_ids))}
- Geometry types: {dict(geometry_counts)}
- Bounds: {[round(v, 6) for v in bounds] if bounds else 'N/A'}
- States: {states}
- Operational status values: {statuses}
- Capacity kV values: {dict(sorted(capacities.items()))}
- Missing values by field: {field_info['missing']}

## Fields

{', '.join(field_info['fields'])}

## Initial assessment

This national line dataset is suitable for screening-level straight-line
distance-to-transmission calculations and contains voltage, operational status,
state, revision and spatial-confidence attributes. It must not be treated as an
engineering asset register or used instead of asset-safety services.
"""
    report_path = config.INFRA_META_DIR / "ga_power_lines_2026_inspection.md"
    report_path.write_text(report, encoding="utf-8")

    # SVG preview
    preview_path = config.INFRA_META_DIR / "ga_power_lines_2026_preview.svg"
    if bounds:
        _generate_power_lines_svg(features, bounds, preview_path)

    if verbose:
        print(f"      Power lines: {len(features)} merged, {len(state_features)} filtered")
    return report_path, preview_path


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------


def _inspect_generators(state: str, fuel_type: str, verbose: bool = False) -> Path:
    """Inspect GA generators and create fuel-type + state subsets."""
    source_path = config.INFRA_DIR / "generators" / "ga_powerstations_2026_australia.geojson"
    collection = load_geojson(source_path)
    features = collection["features"]

    fuel_features = filter_by_fuel_type(features, fuel_type)
    state_features = filter_by_state(fuel_features, state)

    fuel_label = fuel_type.lower().replace(" ", "_")
    state_label = state.lower() if state.upper() != "ALL" else "all"
    output_dir = config.INFRA_DIR / "generators"

    # Write filtered outputs
    for out_path, name, selected in [
        (output_dir / f"ga_{fuel_label}_generators_2026_australia.geojson",
         f"GA {fuel_type.title()} Generators 2026", fuel_features),
        (output_dir / f"ga_{fuel_label}_generators_2026_{state_label}.geojson",
         f"GA {fuel_type.title()} Generators 2026 — {state.upper()}", state_features),
    ]:
        derived = {**collection, "name": name, "features": selected}
        write_geojson(out_path, derived)

    # Stats
    field_info = compute_field_stats(features)
    technologies = count_property(features, "technology_type")
    fuels = count_property(features, "primary_fuel_type")
    statuses = count_property(features, "status")
    fuel_states = count_property(fuel_features, "state")
    valid_coords = count_valid_coordinates(features)

    report = f"""# Geoscience Australia Generators 2026 — Inspection

*Generated by `pipeline.infrastructure.inspect` on {utc_now()}. Do not edit by hand.*

- Source: `https://services.ga.gov.au/gis/rest/services/Electricity_Infrastructure/MapServer/1`
- Custodian: Geoscience Australia
- Attribution: (c) Commonwealth of Australia (Geoscience Australia) 2026
- Format: ArcGIS Feature Service downloaded as GeoJSON
- CRS: EPSG:7844 (GDA2020)
- National feature count: {len(features)}
- Fuel type filter: {fuel_type}
- Filtered feature count (national): {len(fuel_features)}
- State filter: {state.upper()}
- Filtered feature count (state): {len(state_features)}
- Valid point coordinates: {valid_coords}/{len(features)}
- Technology values: {technologies}
- Fuel values: {fuels}
- Generator status values: {statuses}
- {fuel_type.title()} features by state: {fuel_states}
- Missing values by field: {field_info['missing']}

## Initial assessment

The layer provides a useful public reference set for existing generation
facilities and can identify {fuel_type} facilities for later validation. It includes
technology/fuel type, capacity, status and point coordinates.
"""
    report_path = config.INFRA_META_DIR / "ga_generators_2026_inspection.md"
    report_path.write_text(report, encoding="utf-8")
    if verbose:
        print(f"      Generators: {len(fuel_features)} {fuel_type}, "
              f"{len(state_features)} in {state.upper()}")
    return report_path


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run(
    verbose: bool = False,
    state: str = config.DEFAULT_STATE,
    fuel_type: str = config.DEFAULT_FUEL_TYPE,
) -> dict:
    """
    Inspect all infrastructure datasets.

    Returns a summary dict with output paths.
    """
    outputs: list[Path] = []

    print("  Inspecting substations...")
    outputs.append(_inspect_substations(state, verbose))

    print("  Inspecting power lines...")
    report, svg = _inspect_power_lines(state, verbose)
    outputs.extend([report, svg])

    print("  Inspecting generators...")
    outputs.append(_inspect_generators(state, fuel_type, verbose))

    print(f"    {len(outputs)} output(s)")
    return {"reports": outputs}
