"""
Wind analyse stage — aggregation sensitivity analysis for the scoring grid.

Quantifies what aggregating the 250 m Global Wind Atlas grid to ~5 km cells
costs. Reports how each aggregation statistic (mean, median, p90, max)
shifts the distribution and how known wind farm cells rank under each.

This is evidence for Task 5's aggregation decision, not the decision itself.

Importable entry point:
    from pipeline.wind.analyse import run
    result = run(verbose=False)

Output:
    DATA/wind-resource/metadata/aggregation_sensitivity.md
"""

from __future__ import annotations

import csv
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import rasterio

from . import config


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

RASTER_NAME = "gwa_v4_wind-speed_100m_new-england-rez.tif"
FACTOR = config.AGGREGATION_FACTOR  # 20

STATISTICS = {
    "mean": lambda b: b.mean(axis=(1, 3)),
    "median": lambda b: np.median(b, axis=(1, 3)),
    "p90": lambda b: np.percentile(b, 90, axis=(1, 3)),
    "max": lambda b: b.max(axis=(1, 3)),
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _blockify(array: np.ndarray, factor: int) -> np.ndarray:
    """Reshape a 2D array into (rows, factor, cols, factor) blocks."""
    rows, cols = array.shape[0] // factor, array.shape[1] // factor
    trimmed = array[:rows * factor, :cols * factor]
    return trimmed.reshape(rows, factor, cols, factor)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run(verbose: bool = False) -> dict:
    """
    Run the analyse stage: aggregation sensitivity analysis.

    Returns a summary dict with the report path.
    """
    raster_path = config.WIND_DIR / RASTER_NAME
    ref_path = config.WIND_REF_DIR / "nsw_wind_farms_new_england.csv"

    if not raster_path.exists():
        raise FileNotFoundError(f"Wind raster not found: {raster_path}")

    with rasterio.open(raster_path) as src:
        data = src.read(1)
        res = src.res
        farm_cells = []
        if ref_path.exists():
            with ref_path.open() as fh:
                for row in csv.DictReader(fh):
                    r, c = src.index(float(row["longitude"]), float(row["latitude"]))
                    farm_cells.append({"name": row["name"],
                                       "block": (r // FACTOR, c // FACTOR)})

    if not np.isfinite(data).all():
        raise RuntimeError("window contains NoData; aggregation stats would be biased")

    blocks = _blockify(data, FACTOR)
    native_valid = data[np.isfinite(data)]
    aggregated = {name: fn(blocks) for name, fn in STATISTICS.items()}

    cell_km_x = res[0] * FACTOR * 111.32 * np.cos(np.radians(-30.5))
    cell_km_y = res[1] * FACTOR * 111.32

    lines = [
        "# Aggregation Sensitivity — 250 m Native Grid to ~5 km Analysis Cells",
        "",
        f"*Generated by `pipeline.wind.analyse` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Do not edit by hand.*",
        "",
        f"**Input:** `{RASTER_NAME}` (wind speed at 100 m, m/s)",
        f"**Aggregation factor:** {FACTOR} x {FACTOR} native pixels per analysis cell "
        f"({FACTOR * res[0]:.4f} deg ~ {cell_km_x:.1f} km E-W x {cell_km_y:.1f} km N-S)",
        f"**Result:** {data.shape[1]} x {data.shape[0]} native pixels -> "
        f"{blocks.shape[2]} x {blocks.shape[0]} analysis cells",
        "",
        "## Effect on the distribution",
        "",
        "| Statistic | Min | Mean | p90 | Max |",
        "|---|---|---|---|---|",
        f"| Native 250 m grid | {native_valid.min():.3f} | {native_valid.mean():.3f} | "
        f"{np.percentile(native_valid, 90):.3f} | {native_valid.max():.3f} |",
    ]
    for name, grid in aggregated.items():
        lines.append(
            f"| 5 km cells, `{name}` | {grid.min():.3f} | {grid.mean():.3f} | "
            f"{np.percentile(grid, 90):.3f} | {grid.max():.3f} |"
        )

    lines += [
        "",
        "## What each statistic does to the best sites",
        "",
        "| Wind farm | Statistic | Cell value (m/s) | Percentile of all cells |",
        "|---|---|---|---|",
    ]
    if verbose:
        print(f"    Native {data.shape[1]}x{data.shape[0]} px -> "
              f"{blocks.shape[2]}x{blocks.shape[0]} cells at ~{cell_km_x:.1f} km")

    for farm in farm_cells:
        br, bc = farm["block"]
        for name, grid in aggregated.items():
            if not (0 <= br < grid.shape[0] and 0 <= bc < grid.shape[1]):
                continue
            value = float(grid[br, bc])
            pct = float((grid < value).mean() * 100)
            farm.setdefault("pctiles", {})[name] = pct
            lines.append(f"| {farm['name']} | `{name}` | {value:.3f} | p{pct:.0f} |")

    # Interpretation
    best = {f["name"]: max(f["pctiles"], key=f["pctiles"].get)
            for f in farm_cells if f.get("pctiles")}
    disagree = len(set(best.values())) > 1
    max_loss = float(np.mean(aggregated["max"] - aggregated["mean"]))

    lines += [
        "",
        "## Reading",
        "",
        f"Averaging costs **{max_loss:.2f} m/s** across the window: that is the mean gap "
        "between a cell's best 250 m pixel and its 400-pixel average.",
        "",
        (
            "The wind farms disagree about which statistic favours them — "
            + ", ".join(f"{name} ranks highest under `{stat}`" for name, stat in best.items())
            + ". The aggregation choice cannot be settled by picking whichever statistic "
            "makes one example look right."
            if disagree else
            f"Every wind farm ranks highest under `{next(iter(best.values()))}` — "
            "suggestive but rests on a very small sample."
        ) if best else "No reference wind farms available for ranking comparison.",
        "",
        "**This stage does not decide the aggregation method.** It is evidence for Task 5.",
    ]

    config.WIND_META_DIR.mkdir(parents=True, exist_ok=True)
    out = config.WIND_META_DIR / "aggregation_sensitivity.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"    → {out.relative_to(config.PROJECT_ROOT)}")

    return {"report": out}
