"""
Wind inspect stage — examine downloaded GWA raster clips.

Reads each local .tif in the wind directory, computes statistics, and
writes per-raster inspection markdown reports.

Importable entry point:
    from pipeline.wind.inspect import run
    result = run(verbose=False)

Output:
    DATA/wind-resource/metadata/<name>_inspection.md
"""

from __future__ import annotations

import math
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import rasterio

from . import config
from .gwa import human_bytes


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

EARTH_M_PER_DEG = 111_320.0


def _metres_per_pixel(res_deg, centre_lat):
    """Convert degree pixel size to approximate metres."""
    x_m = res_deg[0] * EARTH_M_PER_DEG * math.cos(math.radians(centre_lat))
    y_m = res_deg[1] * EARTH_M_PER_DEG
    return x_m, y_m


def _describe_raster(src, read_data: bool) -> dict:
    """Collect header fields, and value statistics if data is read."""
    centre_lat = (src.bounds.bottom + src.bounds.top) / 2
    x_m, y_m = _metres_per_pixel((abs(src.res[0]), abs(src.res[1])), centre_lat)

    info = {
        "crs": str(src.crs),
        "driver": src.driver,
        "bands": src.count,
        "width": src.width,
        "height": src.height,
        "dtype": src.dtypes[0],
        "nodata": src.nodata,
        "pixel_size_deg": (abs(src.res[0]), abs(src.res[1])),
        "pixel_size_m": (x_m, y_m),
        "centre_lat": centre_lat,
        "bounds": tuple(src.bounds),
        "compression": src.profile.get("compress"),
        "tiled": src.profile.get("tiled"),
        "block_shape": src.block_shapes[0],
        "overviews": src.overviews(1),
        "stats": None,
    }

    if read_data:
        data = src.read(1, masked=True)
        valid = np.ma.masked_invalid(data).compressed()
        total = data.size
        info["stats"] = {
            "total_pixels": total,
            "valid_pixels": int(valid.size),
            "missing_pixels": int(total - valid.size),
            "missing_pct": 100.0 * (total - valid.size) / total if total else 0.0,
            "min": float(valid.min()) if valid.size else float("nan"),
            "max": float(valid.max()) if valid.size else float("nan"),
            "mean": float(valid.mean()) if valid.size else float("nan"),
            "median": float(np.median(valid)) if valid.size else float("nan"),
            "p10": float(np.percentile(valid, 10)) if valid.size else float("nan"),
            "p90": float(np.percentile(valid, 90)) if valid.size else float("nan"),
        }
    return info


def _render_wind_inspection(name: str, source: str, info: dict, extra: dict | None = None) -> str:
    """Render wind raster inspection as markdown."""
    b = info["bounds"]
    lines = [
        f"# Raster Inspection — {name}",
        "",
        f"*Generated by `pipeline.wind.inspect` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Do not edit by hand.*",
        "",
        f"**Source:** {source}",
        "",
        "## Raster Properties",
        "",
        "| Property | Value |",
        "|---|---|",
        f"| CRS | {info['crs']} |",
        f"| Driver | {info['driver']} |",
        f"| Number of bands | {info['bands']} |",
        f"| Grid size (cols x rows) | {info['width']} x {info['height']} |",
        f"| Data type | {info['dtype']} |",
        f"| NoData value | {info['nodata']} |",
        f"| Pixel size (degrees) | {info['pixel_size_deg'][0]:.7g} x {info['pixel_size_deg'][1]:.7g} |",
        f"| Pixel size (approx. metres at lat {info['centre_lat']:.2f}) | "
        f"{info['pixel_size_m'][0]:.0f} m (E-W) x {info['pixel_size_m'][1]:.0f} m (N-S) |",
        f"| Bounds (xmin, ymin, xmax, ymax) | {b[0]:.5f}, {b[1]:.5f}, {b[2]:.5f}, {b[3]:.5f} |",
        f"| Internal tiling | {info['tiled']} (block {info['block_shape'][0]}x{info['block_shape'][1]}) |",
        f"| Compression | {info['compression']} |",
        f"| Overview levels | {info['overviews'] or 'none'} |",
    ]
    for key, value in (extra or {}).items():
        lines.append(f"| {key} | {value} |")

    stats = info["stats"]
    if stats:
        lines += [
            "",
            "## Value Statistics (band 1)",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| Total pixels | {stats['total_pixels']:,} |",
            f"| Valid pixels | {stats['valid_pixels']:,} |",
            f"| Missing (NaN/NoData) pixels | {stats['missing_pixels']:,} |",
            f"| Missing coverage | {stats['missing_pct']:.2f}% |",
            f"| Minimum | {stats['min']:.4f} |",
            f"| 10th percentile | {stats['p10']:.4f} |",
            f"| Median | {stats['median']:.4f} |",
            f"| Mean | {stats['mean']:.4f} |",
            f"| 90th percentile | {stats['p90']:.4f} |",
            f"| Maximum | {stats['max']:.4f} |",
        ]
    return "\n".join(lines) + "\n"


def _inspect_wind_local(path: Path, verbose: bool = False) -> Path:
    """Inspect a local GWA raster clip."""
    with rasterio.open(path) as src:
        info = _describe_raster(src, read_data=True)
    extra = {"File size on disk": human_bytes(path.stat().st_size)}
    if verbose:
        print(f"      {path.name}: {info['width']}x{info['height']} "
              f"missing={info['stats']['missing_pct']:.2f}%")

    content = _render_wind_inspection(
        path.name, str(path.relative_to(config.PROJECT_ROOT)), info, extra
    )
    out_path = config.WIND_META_DIR / f"{path.stem}_inspection.md"
    config.WIND_META_DIR.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    return out_path


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run(verbose: bool = False) -> dict:
    """
    Inspect all local GWA rasters and write inspection reports.

    Returns a summary dict with report paths.
    """
    paths = sorted(config.WIND_DIR.glob("*.tif"))
    outputs = []
    for path in paths:
        outputs.append(_inspect_wind_local(path, verbose))

    print(f"    {len(outputs)} inspection report(s)")
    return {"reports": outputs}
