"""
Wind probe stage — discover which Global Wind Atlas layers are available.

Probes the GWA per-country API via HTTP HEAD (no raster data transferred)
and writes a layer availability report.

Importable entry point:
    from pipeline.wind.probe import run
    result = run(verbose=False)

Output:
    DATA/wind-resource/metadata/layer_availability.md
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import requests

from . import config
from .gwa import api_url, human_bytes
from ..common.geo import atomic_write_text


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _size_range(sizes: list[int]) -> str:
    """Render a size range, collapsing when ends round to the same figure."""
    if not sizes:
        return "—"
    lo, hi = min(sizes) / 1e6, max(sizes) / 1e6
    return f"{lo:.0f} MB" if round(lo) == round(hi) else f"{lo:.0f}–{hi:.0f} MB"


def _probe_gwa_layer(variable: str, height: int | None) -> dict:
    """HEAD the GWA API endpoint and the CDN object it redirects to."""
    endpoint = api_url(variable, height)
    redirect = requests.head(endpoint, allow_redirects=False, timeout=config.GWA_TIMEOUT)
    location = redirect.headers.get("Location")
    if not location:
        return {"available": False, "status": redirect.status_code, "bytes": 0}
    cdn = requests.head(location, timeout=config.GWA_TIMEOUT)
    return {
        "available": cdn.status_code == 200,
        "status": cdn.status_code,
        "bytes": int(cdn.headers.get("Content-Length", 0)),
        "last_modified": cdn.headers.get("Last-Modified", ""),
        "filename": location.split("?")[0].rsplit("/", 1)[-1],
    }


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def run(verbose: bool = False) -> dict:
    """
    Probe GWA layers and write layer_availability.md.

    Returns a summary dict with the output path.
    """
    rows, flat_rows = [], []

    for variable, unit, description in config.GWA_HEIGHT_VARIABLES:
        results = {h: _probe_gwa_layer(variable, h) for h in config.GWA_HEIGHTS}
        if verbose:
            for h, r in results.items():
                print(f"    {variable:<22} {h:<5} {r['status']} {r['bytes'] / 1e6:8.0f} MB")
        sizes = [r["bytes"] for r in results.values() if r["available"]]
        heights_ok = [str(h) for h, r in results.items() if r["available"]]
        rows.append({
            "variable": variable, "unit": unit, "description": description,
            "heights": ", ".join(heights_ok) or "none",
            "size": _size_range(sizes),
            "available": bool(sizes),
            "statuses": sorted({r["status"] for r in results.values()}),
        })

    for variable, unit, description in config.GWA_FLAT_VARIABLES:
        r = _probe_gwa_layer(variable, None)
        if verbose:
            print(f"    {variable:<22} {'-':<5} {r['status']} {r['bytes'] / 1e6:8.0f} MB")
        flat_rows.append({
            "variable": variable, "unit": unit, "description": description,
            "size": f"{r['bytes'] / 1e6:.0f} MB" if r["available"] else "—",
            "available": r["available"], "status": r["status"],
        })

    # Compute total size of the five default samples
    total = sum(
        _probe_gwa_layer(v, h)["bytes"] for v, h in
        [("wind-speed", 50), ("wind-speed", 100), ("wind-speed", 150),
         ("power-density", 100)]
    ) + _probe_gwa_layer("capacity-factor_IEC2", None)["bytes"]

    lines = [
        "# Global Wind Atlas v4 — Layer Availability via the Per-Country API",
        "",
        f"*Generated by `pipeline.wind.probe` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Do not edit by hand.*",
        "",
        "Endpoint probed: `https://globalwindatlas.info/api/gis/country/AUS/<variable>[/<height>]`",
        "Sizes are for full Australian coverage. HEAD requests only — no raster data transferred.",
        "",
        "## Variables published at multiple heights",
        "",
        "| Variable | Units | Heights available (m) | Australia file size | Description |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['variable']}` | {r['unit']} | {r['heights']} | {r['size']} | "
            f"{r['description']} |"
        )

    lines += [
        "",
        "## Variables published without a height parameter",
        "",
        "| Variable | Units | Available? | Australia file size | Description |",
        "|---|---|---|---|---|",
    ]
    for r in flat_rows:
        status = "Yes" if r["available"] else f"**No — HTTP {r['status']}**"
        lines.append(
            f"| `{r['variable']}` | {r['unit']} | {status} | {r['size']} | "
            f"{r['description']} |"
        )

    unavailable = [r["variable"] for r in flat_rows if not r["available"]]
    lines += [
        "",
        "## Notes",
        "",
        f"- **Unavailable through this route:** {', '.join(f'`{v}`' for v in unavailable)}. "
        "These exist in GWA 4 only as global rasters on the DTU repository (RIX 6.1 GB, site "
        "elevation 8.9 GB), or through the web application's interactive area download, which "
        "is not scriptable.",
        "- No seasonal or monthly breakdown is published for any layer. Every layer is a single "
        "long-term mean over 2008–2017.",
        f"- The five layers sampled by this task total **{total / 1e9:.2f} GB** at full "
        "Australian coverage. Windowed `/vsicurl/` reads retrieved about 11 MB of that.",
    ]

    config.WIND_META_DIR.mkdir(parents=True, exist_ok=True)
    out = config.WIND_META_DIR / "layer_availability.md"
    atomic_write_text(out, "\n".join(lines) + "\n")

    print(f"    → {out.relative_to(config.PROJECT_ROOT)}")
    return {"layer_availability": out}
