"""
Quantify what aggregating the 250 m Global Wind Atlas grid to ~5 km cells costs.

This is the highest-severity integration issue on the Task 1 register. The
Product Knowledge Base fixes the analysis grid at ~5 km, but the Atlas is
published at 0.0025 deg (~250 m). Twenty native pixels per side collapse into
one analysis cell, and the choice of aggregation statistic decides whether a
ridge line survives that collapse or is averaged away by the valleys beside it.

The question is not academic. Wind farms are built on ridges. If mean
aggregation buries the ridge signal, the platform will systematically
under-rate exactly the terrain developers target.

This script reports, for the study window:
  - how each statistic shifts the distribution,
  - what the cells containing known operating wind farms score under each,
  - and how those cells rank against all other cells under each.

Usage:
  python scripts/aggregation_sensitivity.py

Output: DATA/wind-resource/metadata/aggregation_sensitivity.md
"""

from __future__ import annotations

import csv
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import rasterio

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "DATA" / "wind-resource"
META_DIR = OUT_DIR / "metadata"
REFERENCE = OUT_DIR / "reference" / "nsw_wind_farms_new_england.csv"

FACTOR = 20  # 20 x 0.0025 deg = 0.05 deg ~ 5.0 km E-W at this latitude, 5.6 km N-S
RASTER = "gwa_v4_wind-speed_100m_new-england-rez.tif"

STATISTICS = {
    "mean": lambda b: b.mean(axis=(1, 3)),
    "median": lambda b: np.median(b, axis=(1, 3)),
    "p90": lambda b: np.percentile(b, 90, axis=(1, 3)),
    "max": lambda b: b.max(axis=(1, 3)),
}


def blockify(array, factor):
    """Reshape a 2-D array into (rows, factor, cols, factor) blocks, trimming any remainder."""
    rows, cols = array.shape[0] // factor, array.shape[1] // factor
    trimmed = array[: rows * factor, : cols * factor]
    return trimmed.reshape(rows, factor, cols, factor)


def main() -> int:
    path = OUT_DIR / RASTER
    with rasterio.open(path) as src:
        data = src.read(1)
        transform, res = src.transform, src.res
        farm_cells = []
        with REFERENCE.open() as fh:
            for row in csv.DictReader(fh):
                r, c = src.index(float(row["longitude"]), float(row["latitude"]))
                farm_cells.append({"name": row["name"], "block": (r // FACTOR, c // FACTOR)})

    if not np.isfinite(data).all():
        raise RuntimeError("window contains NoData; aggregation stats would be biased")

    blocks = blockify(data, FACTOR)
    native_valid = data[np.isfinite(data)]
    aggregated = {name: fn(blocks) for name, fn in STATISTICS.items()}

    cell_km_x = res[0] * FACTOR * 111.32 * np.cos(np.radians(-30.5))
    cell_km_y = res[1] * FACTOR * 111.32

    lines = [
        "# Aggregation Sensitivity — 250 m Native Grid to ~5 km Analysis Cells",
        "",
        f"*Generated by `scripts/aggregation_sensitivity.py` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Do not edit by hand.*",
        "",
        f"**Input:** `{RASTER}` (wind speed at 100 m, m/s)",
        f"**Aggregation factor:** {FACTOR} x {FACTOR} native pixels per analysis cell "
        f"({FACTOR * res[0]:.4f} deg ~ {cell_km_x:.1f} km E-W x {cell_km_y:.1f} km N-S)",
        f"**Result:** {data.shape[1]} x {data.shape[0]} native pixels -> "
        f"{blocks.shape[2]} x {blocks.shape[0]} analysis cells",
        "",
        "## Effect on the distribution",
        "",
        "| Statistic | Min | Mean | p90 | Max |",
        "|---|---|---|---|---|",
        f"| Native 250 m grid | {native_valid.min():.3f} | {native_valid.mean():.3f} | "
        f"{np.percentile(native_valid, 90):.3f} | {native_valid.max():.3f} |",
    ]
    for name, grid in aggregated.items():
        lines.append(
            f"| 5 km cells, `{name}` | {grid.min():.3f} | {grid.mean():.3f} | "
            f"{np.percentile(grid, 90):.3f} | {grid.max():.3f} |"
        )

    lines += [
        "",
        "## What each statistic does to the best sites",
        "",
        "Cells containing a known operating wind farm, scored under each aggregation "
        "statistic, with their rank among all cells in the window.",
        "",
        "| Wind farm | Statistic | Cell value (m/s) | Percentile of all cells |",
        "|---|---|---|---|",
    ]
    print(f"Native {data.shape[1]}x{data.shape[0]} px -> "
          f"{blocks.shape[2]}x{blocks.shape[0]} cells at ~{cell_km_x:.1f} km\n")
    for farm in farm_cells:
        br, bc = farm["block"]
        for name, grid in aggregated.items():
            if not (0 <= br < grid.shape[0] and 0 <= bc < grid.shape[1]):
                continue
            value = float(grid[br, bc])
            pct = float((grid < value).mean() * 100)
            farm.setdefault("pctiles", {})[name] = pct
            lines.append(f"| {farm['name']} | `{name}` | {value:.3f} | p{pct:.0f} |")
            print(f"  {farm['name']:<24} {name:<7} {value:.3f}  p{pct:.0f}")
        print()

    # Which statistic ranks each farm highest? If the farms disagree, no single
    # statistic is universally favourable and the choice needs a stated rationale.
    best = {f["name"]: max(f["pctiles"], key=f["pctiles"].get)
            for f in farm_cells if f.get("pctiles")}
    disagree = len(set(best.values())) > 1

    max_loss = float(np.mean(aggregated["max"] - aggregated["mean"]))
    lines += [
        "",
        "## Reading",
        "",
        f"Averaging costs **{max_loss:.2f} m/s** across the window: that is the mean gap "
        "between a cell's best 250 m pixel and its 400-pixel average. In terrain like the "
        "New England ridge lines the gap is where the wind farms are.",
        "",
        "Compare the percentile columns above, not the values. The question a screening "
        "tool has to answer is whether a cell ranks above its neighbours, and the statistic "
        "changes that ranking, not just the number attached to it.",
        "",
        (
            "The two wind farms disagree about which statistic favours them — "
            + ", ".join(f"{name} ranks highest under `{stat}`" for name, stat in best.items())
            + ". A statistic that flatters one known-good site penalises the other, on the "
            "same raster, in the same window. That is the clearest available evidence that "
            "the aggregation choice cannot be settled by picking whichever statistic makes "
            "one example look right."
            if disagree else
            "Every wind farm in the window ranks highest under the same statistic "
            f"(`{next(iter(best.values()))}`), which is suggestive but rests on a very "
            "small sample."
        ),
        "",
        "Note that no single statistic is obviously right. `mean` answers *what is the "
        "average resource across this cell*; `max` answers *is there anywhere in this cell "
        "worth building*. The second is the question a screening tool is actually asking, "
        "but `max` is also the statistic most sensitive to a single bad pixel, and it "
        "implicitly assumes the best pixel in the cell is developable — which terrain, land "
        "use and protected-area exclusions may later contradict.",
        "",
        "**This script does not decide the aggregation method.** It is evidence for Task 5, "
        "which owns the decision.",
    ]

    META_DIR.mkdir(parents=True, exist_ok=True)
    out = META_DIR / "aggregation_sensitivity.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
