"""
Cross-check the windowed clips against an independently downloaded full raster.

The earlier OptMining prototype (repo `reoz`) downloaded the complete Australian
Global Wind Atlas rasters on 2026-08-06 and recorded SHA-256 sidecars. This task
retrieved the same data two weeks later by an entirely different route — windowed
reads over GDAL /vsicurl/ rather than a full HTTP download.

Comparing them tests two things at once:

  - that a windowed read returns exactly what a full download would have, so the
    approach in download_gwa_sample.py is sound rather than merely convenient; and
  - that GWA v4 has not been revised between the two dates, which matters because
    the rasters carry no embedded version metadata and provenance would otherwise
    rest on a filename.

Skips cleanly when the prototype is not present — it lives outside this repo.

Usage:
  python scripts/crosscheck_against_prototype.py
  python scripts/crosscheck_against_prototype.py --prototype /path/to/OptMining

Output: DATA/wind-resource/metadata/crosscheck_prototype.md
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import rasterio
from rasterio.windows import from_bounds

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "DATA" / "wind-resource"
META_DIR = OUT_DIR / "metadata"
DEFAULT_PROTOTYPE = Path.home() / "Documents" / "Projects" / "OptMining"
BBOX = (150.0, -31.5, 152.0, -29.5)

PAIRS = [
    ("AUS_wind-speed_100m.tif", "gwa_v4_wind-speed_100m_new-england-rez.tif"),
    ("AUS_power-density_100m.tif", "gwa_v4_power-density_100m_new-england-rez.tif"),
]


def display_path(path: Path) -> str:
    """
    Render a path without leaking a personal home directory.

    This report is committed to a shared repository, so an absolute path from one
    developer's machine is both noise and mildly private. Paths under the home
    directory are shown with a ``~`` prefix.
    """
    try:
        return f"~/{path.relative_to(Path.home())}"
    except ValueError:
        return str(path)


def sha256(path: Path, chunk: int = 1 << 22) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(chunk), b""):
            digest.update(block)
    return digest.hexdigest()


def compare(full: Path, clip: Path) -> dict:
    """Read the clip's window from the full raster and compare pixel for pixel."""
    with rasterio.open(full) as src:
        window = from_bounds(*BBOX, transform=src.transform).round_offsets().round_lengths()
        reference = src.read(1, window=window)
    with rasterio.open(clip) as src:
        sampled = src.read(1)

    if reference.shape != sampled.shape:
        return {"file": full.name, "identical": False,
                "note": f"shape mismatch {reference.shape} vs {sampled.shape}"}

    finite = np.isfinite(reference) & np.isfinite(sampled)
    return {
        "file": full.name,
        "identical": bool(np.array_equal(reference, sampled, equal_nan=True)),
        "max_abs_diff": float(np.abs(reference[finite] - sampled[finite]).max())
        if finite.any() else float("nan"),
        "nan_masks_match": bool(np.array_equal(np.isnan(reference), np.isnan(sampled))),
        "shape": list(reference.shape),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--prototype", default=str(DEFAULT_PROTOTYPE),
                        help="Path to the OptMining prototype checkout")
    args = parser.parse_args()

    gwa_dir = Path(args.prototype) / "data" / "raw" / "gwa"
    if not gwa_dir.is_dir():
        print(f"Prototype rasters not found at {gwa_dir} — nothing to cross-check.")
        print("This is not a failure: the prototype lives outside this repository.")
        return 0

    lines = [
        "# Cross-Check — Windowed Reads vs. an Independently Downloaded Raster",
        "",
        f"*Generated by `scripts/crosscheck_against_prototype.py` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Do not edit by hand.*",
        "",
        f"Reference: `{display_path(gwa_dir)}` — full Australian rasters downloaded by the "
        "OptMining prototype (github.com/pouyamousavi1/OptMining) on 2026-08-06 via a full "
        "HTTP download.",
        f"Comparison window: `{BBOX}` (EPSG:4326).",
        "",
        "## Checksums recorded at download vs. the files today",
        "",
        "| File | Recorded SHA-256 | Verifies? |",
        "|---|---|---|",
    ]

    for full_name, _ in PAIRS:
        full = gwa_dir / full_name
        sidecar = gwa_dir / f"{full_name}.sha256.json"
        if not (full.is_file() and sidecar.is_file()):
            continue
        recorded = json.loads(sidecar.read_text())["sha256"]
        ok = sha256(full) == recorded
        print(f"  checksum {full_name}: {'MATCH' if ok else 'DIFFER'}")
        lines.append(f"| `{full_name}` | `{recorded[:16]}…` | "
                     f"{'Yes' if ok else '**No — file changed on disk**'} |")

    lines += [
        "",
        "## Pixel comparison",
        "",
        "| File | Window | Identical? | Max abs difference | NaN masks match |",
        "|---|---|---|---|---|",
    ]
    results = []
    for full_name, clip_name in PAIRS:
        full, clip = gwa_dir / full_name, OUT_DIR / clip_name
        if not (full.is_file() and clip.is_file()):
            continue
        r = compare(full, clip)
        results.append(r)
        print(f"  pixels   {full_name}: "
              f"{'IDENTICAL' if r['identical'] else 'DIFFERS'}")
        lines.append(
            f"| `{full_name}` | {r['shape'][1]} x {r['shape'][0]} | "
            f"{'**Yes**' if r['identical'] else 'No'} | "
            f"{r.get('max_abs_diff', float('nan')):.10g} | "
            f"{'Yes' if r.get('nan_masks_match') else 'No'} |"
        )

    all_identical = results and all(r["identical"] for r in results)
    lines += [
        "",
        "## Conclusion",
        "",
        (
            "Two independent retrieval methods, two weeks apart, return the same pixels. "
            "That validates the windowed `/vsicurl/` approach used by this task, and it "
            "establishes that Global Wind Atlas v4 was not revised between 2026-08-06 and "
            "the date above. The second point matters because the rasters carry no embedded "
            "version metadata, so without a check like this the dataset vintage would rest "
            "on a filename."
            if all_identical else
            "**The two retrievals disagree.** Investigate before relying on either — the "
            "publisher may have revised the data, or one retrieval is faulty."
        ),
    ]

    META_DIR.mkdir(parents=True, exist_ok=True)
    out = META_DIR / "crosscheck_prototype.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
