"""
Shared helpers for Task 4 geographic & environmental data retrieval.

The vector sources (ABS ASGS boundaries, DCCEEW CAPAD protected areas) are
ArcGIS REST FeatureServer layers that serve GeoJSON directly (``f=geojson``),
so no geospatial vector library is needed: features arrive as GeoJSON dicts
and are handled with the standard library. Rasters (SRTM elevation, ABARES
NLUM land use) are read with rasterio, windowed over /vsicurl// vsizip so the
national files are never downloaded in full (Constitution: do not download or
process more data than the analysis requires).

Endpoints:
  ABS ASGS 2021  https://geo.abs.gov.au/arcgis/rest/services/ASGS2021
  CAPAD 2024     https://gis.environment.gov.au/gispubmap/rest/services/ogc_services/CAPAD/FeatureServer
  ABARES NLUM    https://www.agriculture.gov.au/abares/aclump (zip downloads)
  SRTM GL1/GL3   https://opentopography.s3.sdsc.edu/raster/ (public S3 mirror)

Licence: see DATA/geographic/DATA_PROVENANCE.md
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

import requests

from gwa_common import apply_vsicurl_env, human_bytes  # noqa: F401  (re-exported)

REPO_ROOT = Path(__file__).resolve().parent.parent
GEO_DIR = REPO_ROOT / "DATA" / "geographic"
META_DIR = GEO_DIR / "metadata"
RAW_DIR = GEO_DIR / "raw"

TIMEOUT = 120

# Study window shared with Task 1 (New England REZ, NSW) so Task 5 can overlay
# wind, infrastructure and geographic samples on the same ground.
DEFAULT_BBOX = (150.0, -31.5, 152.0, -29.5)
DEFAULT_AREA = "new-england-rez"

# ArcGIS REST layer endpoints verified live during planning (2026-08-20).
ABS_ASGS_BASE = "https://geo.abs.gov.au/arcgis/rest/services/ASGS2021"
CAPAD_BASE = (
    "https://gis.environment.gov.au/gispubmap/rest/services/ogc_services/CAPAD/FeatureServer"
)


def apply_geo_vsicurl_env() -> None:
    """
    GDAL env for remote reads. Unlike Task 1 (bare .tif URLs), the SRTM
    mosaics are .vrt indexes referencing .tif tiles, and NLUM is read through
    /vsizip/, so the allowed-extension list must cover all three.
    """
    os.environ["GDAL_DISABLE_READDIR_ON_OPEN"] = "EMPTY_DIR"
    os.environ["CPL_VSIL_CURL_ALLOWED_EXTENSIONS"] = ".tif,.vrt,.zip"
    os.environ.setdefault("GDAL_HTTP_MAX_RETRY", "3")
    os.environ.setdefault("GDAL_HTTP_RETRY_DELAY", "2")


def utc_now() -> str:
    """Timestamp used across manifests and report banners."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def banner(script_name: str) -> str:
    """Standard do-not-edit banner for generated markdown reports."""
    return f"*Generated by `scripts/{script_name}` on {utc_now()}. Do not edit by hand.*\n"


def atomic_write_text(path: Path, text: str) -> None:
    """Write via a sibling tmp file + rename so re-runs and interrupts are safe."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(text)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def atomic_write_json(path: Path, obj: object) -> None:
    atomic_write_text(path, json.dumps(obj, indent=2) + "\n")


def layer_metadata(layer_url: str) -> dict:
    """Read an ArcGIS REST layer's JSON metadata (no feature data transferred)."""
    resp = requests.get(layer_url, params={"f": "json"}, timeout=TIMEOUT)
    resp.raise_for_status()
    meta = resp.json()
    if "error" in meta:
        raise RuntimeError(f"{layer_url} returned an ArcGIS error: {meta['error']}")
    return meta


def layer_count(layer_url: str, where: str = "1=1") -> int:
    """Feature count for a layer, optionally filtered."""
    resp = requests.get(
        f"{layer_url}/query",
        params={"where": where, "returnCountOnly": "true", "f": "json"},
        timeout=TIMEOUT,
    )
    resp.raise_for_status()
    body = resp.json()
    if "count" not in body:
        raise RuntimeError(f"{layer_url} count query failed: {body}")
    return int(body["count"])


def esri_rings_to_geojson(geometry: dict) -> dict:
    """
    Convert an Esri JSON polygon geometry to GeoJSON.

    Fallback for layers that refuse f=geojson. Esri rings do not distinguish
    exterior from hole, so every ring becomes its own polygon in a MultiPolygon;
    for point-in-polygon and rasterisation with even-odd filling this is
    equivalent, and no sample in this task is used for anything finer.
    """
    rings = geometry.get("rings")
    if not rings:
        raise ValueError("geometry has no rings")
    return {"type": "MultiPolygon", "coordinates": [[ring] for ring in rings]}


def query_layer_geojson(
    layer_url: str,
    where: str = "1=1",
    out_fields: str = "*",
    out_sr: int = 4326,
    geometry_bbox: tuple[float, float, float, float] | None = None,
    max_allowable_offset: float | None = None,
    page_size: int = 1000,
) -> dict:
    """
    Query an ArcGIS FeatureServer layer, paging until exhausted, and return a
    GeoJSON FeatureCollection.

    ``out_sr`` is always sent explicitly: some services (ABS) default to Web
    Mercator, and an implicit CRS is exactly the silent mismatch the
    Constitution forbids. ``geometry_bbox`` (W, S, E, N in EPSG:4326) becomes
    an envelope intersection filter. ``max_allowable_offset`` (in out_sr
    units) requests server-side generalisation for national files that would
    otherwise be too large to commit; callers must record it in the manifest.
    """
    features: list[dict] = []
    offset = 0
    while True:
        params: dict[str, object] = {
            "where": where,
            "outFields": out_fields,
            "outSR": out_sr,
            "f": "geojson",
            "resultOffset": offset,
            "resultRecordCount": page_size,
        }
        if geometry_bbox is not None:
            w, s, e, n = geometry_bbox
            params.update(
                geometry=f"{w},{s},{e},{n}",
                geometryType="esriGeometryEnvelope",
                inSR=4326,
                spatialRel="esriSpatialRelIntersects",
            )
        if max_allowable_offset is not None:
            params["maxAllowableOffset"] = max_allowable_offset

        resp = requests.get(f"{layer_url}/query", params=params, timeout=TIMEOUT)
        resp.raise_for_status()
        page = resp.json()
        if "error" in page:
            raise RuntimeError(f"{layer_url} query failed: {page['error']}")

        page_features = page.get("features", [])
        features.extend(page_features)
        # GeoJSON responses flag continuation differently across server
        # versions; absence of both markers plus a short page means done.
        more = page.get("exceededTransferLimit") or (
            page.get("properties", {}).get("exceededTransferLimit")
            if isinstance(page.get("properties"), dict)
            else False
        )
        if not more and len(page_features) < page_size:
            break
        offset += len(page_features)
        if not page_features:  # defensive: server said "more" but sent nothing
            break

    return {"type": "FeatureCollection", "features": features}


def feature_collection_bytes(collection: dict) -> int:
    """Serialised size of a FeatureCollection, for the <10 MB commit guardrail."""
    return len(json.dumps(collection).encode())
