"""
Inspect a Global Wind Atlas raster and write a metadata record.

Reports exactly the fields Section 6 of the Task 1 investigation document asks
for: band count, pixel size, NoData value, data type, CRS, bounds, plus value
statistics and missing-data coverage. Every figure quoted in the task document
comes from this script's output rather than being written by hand.

Can inspect a local clip or read the header of a remote country raster through
/vsicurl/ without downloading it.

Usage:
  python scripts/inspect_gwa_raster.py --input DATA/wind-resource/*.tif
  python scripts/inspect_gwa_raster.py --remote wind-speed --height 100
  python scripts/inspect_gwa_raster.py --all-local

Output: DATA/wind-resource/metadata/<name>_inspection.md
"""

from __future__ import annotations

import argparse
import math
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import rasterio
from rasterio.enums import Resampling

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gwa_common import apply_vsicurl_env, human_bytes, resolve_source  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "DATA" / "wind-resource"
META_DIR = OUT_DIR / "metadata"

EARTH_M_PER_DEG = 111_320.0  # metres per degree of latitude (spherical approximation)


def metres_per_pixel(res_deg, centre_lat):
    """
    Convert a degree pixel size to approximate metres.

    EPSG:4326 pixels are square in degrees but not in metres: the north-south
    size is constant while the east-west size shrinks with the cosine of the
    latitude. Both are reported so the document can state the resolution
    honestly instead of repeating a nominal '250 m'.
    """
    x_m = res_deg[0] * EARTH_M_PER_DEG * math.cos(math.radians(centre_lat))
    y_m = res_deg[1] * EARTH_M_PER_DEG
    return x_m, y_m


def describe(src, read_data: bool):
    """Collect the header fields, and value statistics when data is read."""
    centre_lat = (src.bounds.bottom + src.bounds.top) / 2
    x_m, y_m = metres_per_pixel((abs(src.res[0]), abs(src.res[1])), centre_lat)

    info = {
        "crs": str(src.crs),
        "driver": src.driver,
        "bands": src.count,
        "width": src.width,
        "height": src.height,
        "dtype": src.dtypes[0],
        "nodata": src.nodata,
        "pixel_size_deg": (abs(src.res[0]), abs(src.res[1])),
        "pixel_size_m": (x_m, y_m),
        "centre_lat": centre_lat,
        "bounds": tuple(src.bounds),
        "compression": src.profile.get("compress"),
        "tiled": src.profile.get("tiled"),
        "block_shape": src.block_shapes[0],
        "overviews": src.overviews(1),
        "stats": None,
    }

    if read_data:
        data = src.read(1, masked=True)
        # GWA marks missing pixels with NaN; mask them explicitly so statistics
        # are computed over real observations only.
        valid = np.ma.masked_invalid(data).compressed()
        total = data.size
        info["stats"] = {
            "total_pixels": total,
            "valid_pixels": int(valid.size),
            "missing_pixels": int(total - valid.size),
            "missing_pct": 100.0 * (total - valid.size) / total if total else 0.0,
            "min": float(valid.min()) if valid.size else float("nan"),
            "max": float(valid.max()) if valid.size else float("nan"),
            "mean": float(valid.mean()) if valid.size else float("nan"),
            "median": float(np.median(valid)) if valid.size else float("nan"),
            "p10": float(np.percentile(valid, 10)) if valid.size else float("nan"),
            "p90": float(np.percentile(valid, 90)) if valid.size else float("nan"),
        }
    return info


def render(name: str, source: str, info: dict, extra: dict | None = None) -> str:
    b = info["bounds"]
    lines = [
        f"# Raster Inspection — {name}",
        "",
        f"*Generated by `scripts/inspect_gwa_raster.py` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Do not edit by hand.*",
        "",
        f"**Source:** {source}",
        "",
        "## Raster Properties",
        "",
        "| Property | Value |",
        "|---|---|",
        f"| CRS | {info['crs']} |",
        f"| Driver | {info['driver']} |",
        f"| Number of bands | {info['bands']} |",
        f"| Grid size (cols x rows) | {info['width']} x {info['height']} |",
        f"| Data type | {info['dtype']} |",
        f"| NoData value | {info['nodata']} |",
        f"| Pixel size (degrees) | {info['pixel_size_deg'][0]:.7g} x {info['pixel_size_deg'][1]:.7g} |",
        f"| Pixel size (approx. metres at lat {info['centre_lat']:.2f}) | "
        f"{info['pixel_size_m'][0]:.0f} m (E-W) x {info['pixel_size_m'][1]:.0f} m (N-S) |",
        f"| Bounds (xmin, ymin, xmax, ymax) | {b[0]:.5f}, {b[1]:.5f}, {b[2]:.5f}, {b[3]:.5f} |",
        f"| Internal tiling | {info['tiled']} (block {info['block_shape'][0]}x{info['block_shape'][1]}) |",
        f"| Compression | {info['compression']} |",
        f"| Overview levels | {info['overviews'] or 'none'} |",
    ]
    for key, value in (extra or {}).items():
        lines.append(f"| {key} | {value} |")

    stats = info["stats"]
    if stats:
        lines += [
            "",
            "## Value Statistics (band 1)",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| Total pixels | {stats['total_pixels']:,} |",
            f"| Valid pixels | {stats['valid_pixels']:,} |",
            f"| Missing (NaN/NoData) pixels | {stats['missing_pixels']:,} |",
            f"| Missing coverage | {stats['missing_pct']:.2f}% |",
            f"| Minimum | {stats['min']:.4f} |",
            f"| 10th percentile | {stats['p10']:.4f} |",
            f"| Median | {stats['median']:.4f} |",
            f"| Mean | {stats['mean']:.4f} |",
            f"| 90th percentile | {stats['p90']:.4f} |",
            f"| Maximum | {stats['max']:.4f} |",
        ]
    else:
        lines += [
            "",
            "## Value Statistics",
            "",
            "Not computed — header read only. The full-country raster was not downloaded; "
            "only its header was read over `/vsicurl/`.",
        ]
    return "\n".join(lines) + "\n"


def write_record(slug: str, content: str) -> Path:
    META_DIR.mkdir(parents=True, exist_ok=True)
    path = META_DIR / f"{slug}_inspection.md"
    path.write_text(content)
    print(f"  wrote {path.relative_to(REPO_ROOT)}")
    return path


def inspect_local(path: Path) -> None:
    print(f"\n{path.name}")
    with rasterio.open(path) as src:
        info = describe(src, read_data=True)
    extra = {"File size on disk": human_bytes(path.stat().st_size)}
    print(f"  {info['crs']}  {info['width']}x{info['height']}  {info['dtype']}  "
          f"nodata={info['nodata']}  missing={info['stats']['missing_pct']:.2f}%")
    print(f"  min={info['stats']['min']:.3f} mean={info['stats']['mean']:.3f} "
          f"max={info['stats']['max']:.3f}")
    write_record(path.stem, render(path.name, str(path.relative_to(REPO_ROOT)), info, extra))


def summarise_decimated(src, factor: int) -> dict:
    """
    Summarise a whole raster by reading its overview pyramid rather than its pixels.

    GWA rasters ship with overviews at 2, 4, ... 64x, so a national summary costs a
    few MB instead of 600. The figures are approximate by construction — each
    overview pixel is an average of the level below it — and are used only to
    describe coverage, never as an analysis input.
    """
    width, height = src.width // factor, src.height // factor
    data = src.read(1, out_shape=(height, width), resampling=Resampling.average)
    valid = data[np.isfinite(data)]
    return {
        "factor": factor,
        "shape": (data.shape[1], data.shape[0]),
        "total": int(data.size),
        "valid": int(valid.size),
        "valid_pct": 100.0 * valid.size / data.size if data.size else 0.0,
        "min": float(valid.min()), "max": float(valid.max()),
        "mean": float(valid.mean()), "median": float(np.median(valid)),
        "p90": float(np.percentile(valid, 90)),
    }


def render_decimated(summary: dict) -> list[str]:
    return [
        "",
        "## Whole-Raster Summary (decimated)",
        "",
        f"Read at overview level {summary['factor']} "
        f"({summary['shape'][0]} x {summary['shape'][1]} pixels) rather than at native "
        "resolution. Approximate by construction — descriptive only, never an analysis input.",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Pixels with data | {summary['valid']:,} of {summary['total']:,} "
        f"({summary['valid_pct']:.1f}% of the bounding box) |",
        f"| Minimum | {summary['min']:.3f} |",
        f"| Median | {summary['median']:.3f} |",
        f"| Mean | {summary['mean']:.3f} |",
        f"| 90th percentile | {summary['p90']:.3f} |",
        f"| Maximum | {summary['max']:.3f} |",
        "",
        "**The valid-pixel figure covers Australian territory including marine areas, not "
        "land.** Statistics computed over it are inflated by ocean, where the Atlas shows "
        "its strongest wind speeds. Compare against a land-only window before drawing any "
        "conclusion from these numbers.",
    ]


def inspect_remote(variable: str, height: int | None, decimate: int | None = None) -> None:
    apply_vsicurl_env()
    provenance = resolve_source(variable, height)
    label = f"{variable}" + (f" @ {height}m" if height is not None else "")
    print(f"\n{label} (full Australia, header only)")
    with rasterio.open(f"/vsicurl/{provenance['signed_url']}") as src:
        info = describe(src, read_data=False)
        summary = summarise_decimated(src, decimate) if decimate else None
    extra = {
        "Remote file size": human_bytes(provenance["remote_bytes"]),
        "Last modified (server)": provenance["last_modified"],
        "API endpoint": provenance["api_endpoint"],
    }
    print(f"  {info['crs']}  {info['width']}x{info['height']}  {info['dtype']}  "
          f"nodata={info['nodata']}  {human_bytes(provenance['remote_bytes'])}")
    suffix = f"_{height}m" if height is not None else ""
    slug = f"gwa_v4_{variable}{suffix}_australia_full"
    content = render(f"{label} — full Australia coverage", provenance["source_url"], info, extra)
    if summary:
        print(f"  decimated {summary['factor']}x: {summary['valid_pct']:.1f}% has data, "
              f"mean {summary['mean']:.2f}, max {summary['max']:.2f}")
        content += "\n".join(render_decimated(summary)) + "\n"
    write_record(slug, content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", nargs="*", help="Local GeoTIFF(s) to inspect")
    parser.add_argument("--all-local", action="store_true",
                        help="Inspect every .tif in DATA/wind-resource/")
    parser.add_argument("--remote", help="Inspect the header of a full-country raster")
    parser.add_argument("--height", type=int, help="Height in metres for --remote")
    parser.add_argument("--decimate", type=int, metavar="N",
                        help="With --remote, also summarise the whole raster by reading its "
                             "overview pyramid at 1/N resolution (use 64 for a national view)")
    args = parser.parse_args()

    if not (args.input or args.all_local or args.remote):
        parser.error("give --input, --all-local or --remote")

    if args.remote:
        inspect_remote(args.remote, args.height, args.decimate)

    paths = [Path(p) for p in (args.input or [])]
    if args.all_local:
        paths += sorted(OUT_DIR.glob("*.tif"))
    for path in paths:
        inspect_local(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
