"""
Probe which Global Wind Atlas layers are available through the per-country API.

The Product Knowledge Base assumed the Atlas would supply roughness and
orography. It does not, and finding out which layers are actually reachable
required probing every variable/height combination rather than reading the
documentation. This script records that result so the availability table in the
Task 1 document is reproducible instead of hand-typed.

The probe uses HTTP HEAD only — it reads response headers and transfers no
raster data.

Usage:
  python scripts/probe_gwa_layers.py

Output: DATA/wind-resource/metadata/layer_availability.md
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gwa_common import api_url  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
META_DIR = REPO_ROOT / "DATA" / "wind-resource" / "metadata"
TIMEOUT = 60

HEIGHTS = [10, 50, 100, 150, 200]
HEIGHT_VARIABLES = [
    ("wind-speed", "m/s", "10-year mean wind speed"),
    ("power-density", "W/m^2", "10-year mean wind power density"),
    ("air-density", "kg/m^3", "Modelled air density"),
    ("combined-Weibull-A", "m/s", "All-sector Weibull scale parameter"),
    ("combined-Weibull-k", "-", "All-sector Weibull shape parameter"),
]
FLAT_VARIABLES = [
    ("capacity-factor_IEC1", "ratio", "IEC class 1 turbine, 100 m hub, 117 m rotor"),
    ("capacity-factor_IEC2", "ratio", "IEC class 2 turbine, 100 m hub, 136 m rotor"),
    ("capacity-factor_IEC3", "ratio", "IEC class 3 turbine, 100 m hub, 150 m rotor"),
    ("capacity-factor_offshore", "ratio", "Offshore turbine, 150 m hub, 150 m rotor"),
    ("RIX", "%", "Ruggedness index — area within 3.5 km with slopes over 30 degrees"),
    ("elevation", "m", "Site elevation used by the Atlas"),
]


def size_range(sizes: list[int]) -> str:
    """Render a size range, collapsing it when the ends round to the same figure."""
    if not sizes:
        return "—"
    lo, hi = min(sizes) / 1e6, max(sizes) / 1e6
    return f"{lo:.0f} MB" if round(lo) == round(hi) else f"{lo:.0f}–{hi:.0f} MB"


def probe(variable: str, height: int | None) -> dict:
    """HEAD the API endpoint and the CDN object it redirects to."""
    endpoint = api_url(variable, height)
    redirect = requests.head(endpoint, allow_redirects=False, timeout=TIMEOUT)
    location = redirect.headers.get("Location")
    if not location:
        return {"available": False, "status": redirect.status_code, "bytes": 0}
    cdn = requests.head(location, timeout=TIMEOUT)
    return {
        "available": cdn.status_code == 200,
        "status": cdn.status_code,
        "bytes": int(cdn.headers.get("Content-Length", 0)),
        "last_modified": cdn.headers.get("Last-Modified", ""),
        "filename": location.split("?")[0].rsplit("/", 1)[-1],
    }


def main() -> int:
    rows, flat_rows = [], []

    for variable, unit, description in HEIGHT_VARIABLES:
        results = {h: probe(variable, h) for h in HEIGHTS}
        for h, r in results.items():
            print(f"  {variable:<22} {h:<5} {r['status']} {r['bytes'] / 1e6:8.0f} MB")
        sizes = [r["bytes"] for r in results.values() if r["available"]]
        heights_ok = [str(h) for h, r in results.items() if r["available"]]
        rows.append({
            "variable": variable, "unit": unit, "description": description,
            "heights": ", ".join(heights_ok) or "none",
            "size": size_range(sizes),
            "available": bool(sizes),
            "statuses": sorted({r["status"] for r in results.values()}),
        })

    for variable, unit, description in FLAT_VARIABLES:
        r = probe(variable, None)
        print(f"  {variable:<22} {'-':<5} {r['status']} {r['bytes'] / 1e6:8.0f} MB")
        flat_rows.append({
            "variable": variable, "unit": unit, "description": description,
            "size": f"{r['bytes'] / 1e6:.0f} MB" if r["available"] else "—",
            "available": r["available"], "status": r["status"],
        })

    total = sum(
        probe(v, h)["bytes"] for v, h in
        [("wind-speed", 50), ("wind-speed", 100), ("wind-speed", 150),
         ("power-density", 100)]
    ) + probe("capacity-factor_IEC2", None)["bytes"]

    lines = [
        "# Global Wind Atlas v4 — Layer Availability via the Per-Country API",
        "",
        f"*Generated by `scripts/probe_gwa_layers.py` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. Do not edit by hand.*",
        "",
        "Endpoint probed: `https://globalwindatlas.info/api/gis/country/AUS/<variable>[/<height>]`",
        "Sizes are for full Australian coverage. HEAD requests only — no raster data transferred.",
        "",
        "## Variables published at multiple heights",
        "",
        "| Variable | Units | Heights available (m) | Australia file size | Description |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(f"| `{r['variable']}` | {r['unit']} | {r['heights']} | {r['size']} | "
                     f"{r['description']} |")

    lines += [
        "",
        "## Variables published without a height parameter",
        "",
        "| Variable | Units | Available? | Australia file size | Description |",
        "|---|---|---|---|---|",
    ]
    for r in flat_rows:
        status = "Yes" if r["available"] else f"**No — HTTP {r['status']}**"
        lines.append(f"| `{r['variable']}` | {r['unit']} | {status} | {r['size']} | "
                     f"{r['description']} |")

    unavailable = [r["variable"] for r in flat_rows if not r["available"]]
    lines += [
        "",
        "## Notes",
        "",
        f"- **Unavailable through this route:** {', '.join(f'`{v}`' for v in unavailable)}. "
        "These exist in GWA 4 only as global rasters on the DTU repository (RIX 6.1 GB, site "
        "elevation 8.9 GB), or through the web application's interactive area download, which "
        "is not scriptable.",
        "- No seasonal or monthly breakdown is published for any layer. Every layer is a single "
        "long-term mean over 2008–2017.",
        f"- The five layers sampled by this task total **{total / 1e9:.2f} GB** at full "
        "Australian coverage. Windowed `/vsicurl/` reads retrieved about 11 MB of that.",
    ]

    META_DIR.mkdir(parents=True, exist_ok=True)
    out = META_DIR / "layer_availability.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
