"""
Explanation — deterministic site-level explanations (stage `explanation`, S2-06a + S2-06b).

Position in the pipeline sequence: `explanation` is registered in
`config.STAGES` immediately AFTER `scoring` (S2-05, which produces the sole
input — the Scored_Table with its per-criterion `contrib_{feature}` columns)
and BEFORE `shortlist`:

    ... → integration → scoring → explanation → shortlist → validate → sanity

WHAT THIS STAGE DOES
--------------------
The scoring stage retains, for every eligible cell, the additive contribution
of each criterion to that cell's score (`contrib_{feature}`) but no
human-readable narrative. This stage turns those contributions into a
structured, deterministic explanation: for each ELIGIBLE cell it names the
cell's strongest positive factors and its important weaknesses, in
screening-level language ("higher-ranked candidate under the selected
assumptions", never "best site").

S2-06a owns the explanation ENGINE and the ELIGIBLE-cell path. S2-06b EXTENDS
the same schema IN PLACE (it does not fork it) with:
  - the EXCLUDED-cell path — a record stating the machine- and human-readable
    exclusion reason(s) from the integrated table's `exclusion_reasons` (the
    F16 {code, text} pairs, Decision-Engine Spec §6.5);
  - PROXY caveats — a caveat for any proxy variable the cell used (marked
    `proxy: true` in the templates), so the demand proxy is never read as
    measured local demand;
  - DATA-QUALITY notes — the cell's S1-09 composite confidence level on every
    record, with reduced-confidence reasons appended when present.
The proxy and data-quality caveats appear on BOTH paths (AC7).

DETERMINISTIC, NO LLM
---------------------
Explanations are template/rule-based, not generated by a language model. The
same Scored_Table and the same template/weights configuration always produce
byte-identical explanations. This is a deliberate MVP choice: a deterministic
rule engine is more auditable than an LLM and cannot hallucinate a factor the
data does not support (guidance Step 6).

HOW FACTORS ARE CHOSEN (design decisions 2A + 3C)
-------------------------------------------------
- RANKING is by contribution magnitude: the criteria contributing the most
  points to a cell's score become its positive factors; the criteria the cell
  scores POORLY on become its weaknesses. The engine reads the persisted
  `contrib_{feature}` values — it never recomputes a score.
- QUALITATIVE BANDS ("top decile", "strong", "moderate", "poor") are derived
  from the cell's NORMALISED value for each criterion. Because the Scored_Table
  does not persist the `norm_{feature}` intermediates, this stage RECOMPUTES
  them deterministically from the integrated table using the SAME shared code
  the scoring stage uses (`pipeline.scoring.normalise.compute_bounds` over the
  eligible population + `normalise_frame`), driven by the SAME weights config.
  There is deliberately no second normaliser. A reconciliation guard asserts
  the recomputed normalised values reproduce the persisted contributions within
  `scoring.config.RECONCILE_TOLERANCE`, so the bands are provably derived from
  the values that produced the score.
- PHRASING is DATA, not code: per-criterion phrases and band thresholds live in
  `explanation_templates.yaml`, loaded and validated at runtime, mirroring the
  weights-as-data principle of `scoring/scoring_weights.yaml`.

Modules:
    config    — Paths, filenames, schema field names and band thresholds. Input
                paths and vocabularies are composed from the producing domain's
                config (scoring, integration), never re-typed as literals.
    templates — `ExplanationTemplates` / `load_templates`: parses and validates
                the phrase/band YAML, failing before any output is written.
    bands     — Maps a normalised value to a qualitative band label, honouring
                the boolean and constant-criterion policies of `normalise.py`.
    engine    — `explain_cell`: the PURE rule engine (a cell's contributions +
                norms + bands + templates in, an Explanation dict out; no I/O).
    load      — Reads the Scored_Table + integrated table, recomputes the
                eligible-population norms/bands via `scoring.normalise`, and
                applies the reconciliation guard. The only file-reading path.
    write     — Atomic JSON + CSV writers for the Explanation_Table and the
                schema document (the frozen contract S2-06b/S2-08 consume).
    report    — Method report, validation report and the provenance triple.
    validate  — No-silent-passes checks over the Explanation_Table.
    run       — Stage entry point: `run(verbose=False, ...) -> dict`.

Usage:
    from pipeline.explanation.run import run
    summary = run(verbose=True)

    # or the pure engine directly, on an in-memory cell:
    from pipeline.explanation.engine import explain_cell
    from pipeline.explanation.templates import load_templates
"""
