"""
Shared helpers for geographic & environmental data retrieval.

The vector sources (ABS ASGS boundaries, DCCEEW CAPAD protected areas) are
ArcGIS REST FeatureServer layers that serve GeoJSON directly (``f=geojson``),
so no geospatial vector library is needed. Rasters (SRTM elevation, ABARES
NLUM land use) are read with rasterio, windowed over /vsicurl/ or /vsizip/
so national files are never downloaded in full.

This module also contains generic utilities (atomic writes, banners,
human_bytes, sha256_file) shared across all domain subpackages.

Licence: see DATA/geographic/DATA_PROVENANCE.md
"""

from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path

import requests

from .. import config


# ---------------------------------------------------------------------------
# Generic utilities
# ---------------------------------------------------------------------------


def human_bytes(n: int) -> str:
    """
    Format a byte count for logs and provenance tables.

    Decimal (1 MB = 10**6 bytes), matching the sizes quoted in the download
    manifest and the task documents.
    """
    step = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if step < 1000 or unit == "GB":
            return f"{step:.1f} {unit}"
        step /= 1000
    return f"{step:.1f} GB"


def sha256_file(path: Path) -> str:
    """
    SHA-256 hex digest of a file, read in 1 MiB chunks so multi-megabyte
    GeoPackages never have to be loaded into memory whole. Raises
    FileNotFoundError for a missing path.
    """
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


# ---------------------------------------------------------------------------
# GDAL environment
# ---------------------------------------------------------------------------


def apply_vsicurl_env() -> None:
    """
    GDAL env for remote reads. The SRTM mosaics are .vrt indexes referencing
    .tif tiles, and NLUM is read through /vsizip/, so the allowed-extension
    list covers .tif, .vrt and .zip.
    """
    for key, value in config.VSICURL_ENV.items():
        os.environ.setdefault(key, value)


# ---------------------------------------------------------------------------
# Timestamps and banners
# ---------------------------------------------------------------------------


def utc_now() -> str:
    """Timestamp used across manifests and report banners."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def banner(module_name: str) -> str:
    """Standard do-not-edit banner for generated markdown reports."""
    return (
        f"*Generated by `pipeline.{module_name}` on {utc_now()}. "
        f"Do not edit by hand.*\n"
    )


# ---------------------------------------------------------------------------
# Atomic file writes
# ---------------------------------------------------------------------------


def atomic_write_text(path: Path, text: str) -> None:
    """Write via a sibling tmp file + rename so re-runs and interrupts are safe."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    try:
        tmp.write_text(text)
        os.replace(tmp, path)
    finally:
        tmp.unlink(missing_ok=True)


def atomic_write_json(path: Path, obj: object) -> None:
    """Atomically write a JSON file with 2-space indentation."""
    atomic_write_text(path, json.dumps(obj, indent=2) + "\n")


# ---------------------------------------------------------------------------
# ArcGIS REST helpers
# ---------------------------------------------------------------------------


def layer_metadata(layer_url: str) -> dict:
    """Read an ArcGIS REST layer's JSON metadata (no feature data transferred)."""
    resp = requests.get(layer_url, params={"f": "json"}, timeout=config.TIMEOUT)
    resp.raise_for_status()
    meta = resp.json()
    if "error" in meta:
        raise RuntimeError(f"{layer_url} returned an ArcGIS error: {meta['error']}")
    return meta


def layer_count(layer_url: str, where: str = "1=1") -> int:
    """Feature count for a layer, optionally filtered."""
    resp = requests.get(
        f"{layer_url}/query",
        params={"where": where, "returnCountOnly": "true", "f": "json"},
        timeout=config.TIMEOUT,
    )
    resp.raise_for_status()
    body = resp.json()
    if "count" not in body:
        raise RuntimeError(f"{layer_url} count query failed: {body}")
    return int(body["count"])


def esri_rings_to_geojson(geometry: dict) -> dict:
    """
    Convert an Esri JSON polygon geometry to GeoJSON.

    Fallback for layers that refuse f=geojson. Every ring becomes its own
    polygon in a MultiPolygon; for point-in-polygon and rasterisation with
    even-odd filling this is equivalent.
    """
    rings = geometry.get("rings")
    if not rings:
        raise ValueError("geometry has no rings")
    return {"type": "MultiPolygon", "coordinates": [[ring] for ring in rings]}


def query_layer_geojson(
    layer_url: str,
    where: str = "1=1",
    out_fields: str = "*",
    out_sr: int = 4326,
    geometry_bbox: tuple[float, float, float, float] | None = None,
    max_allowable_offset: float | None = None,
    page_size: int = 1000,
) -> dict:
    """
    Query an ArcGIS FeatureServer layer, paging until exhausted, and return a
    GeoJSON FeatureCollection.

    ``out_sr`` is always sent explicitly: some services (ABS) default to Web
    Mercator, and an implicit CRS is exactly the silent mismatch the
    Constitution forbids.
    """
    features: list[dict] = []
    offset = 0
    while True:
        params: dict[str, object] = {
            "where": where,
            "outFields": out_fields,
            "outSR": out_sr,
            "f": "geojson",
            "resultOffset": offset,
            "resultRecordCount": page_size,
        }
        if geometry_bbox is not None:
            w, s, e, n = geometry_bbox
            params.update(
                geometry=f"{w},{s},{e},{n}",
                geometryType="esriGeometryEnvelope",
                inSR=4326,
                spatialRel="esriSpatialRelIntersects",
            )
        if max_allowable_offset is not None:
            params["maxAllowableOffset"] = max_allowable_offset

        resp = requests.get(f"{layer_url}/query", params=params, timeout=config.TIMEOUT)
        resp.raise_for_status()
        page = resp.json()
        if "error" in page:
            raise RuntimeError(f"{layer_url} query failed: {page['error']}")

        page_features = page.get("features", [])
        features.extend(page_features)

        more = page.get("exceededTransferLimit") or (
            page.get("properties", {}).get("exceededTransferLimit")
            if isinstance(page.get("properties"), dict)
            else False
        )
        if not more and len(page_features) < page_size:
            break
        offset += len(page_features)
        if not page_features:
            break

    return {"type": "FeatureCollection", "features": features}


def feature_collection_bytes(collection: dict) -> int:
    """Serialised size of a FeatureCollection, for the <10 MB commit guardrail."""
    return len(json.dumps(collection).encode())
